### ISSUE TITLE
Fix the support for multiple deployers

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1006]
#586 should have introduced the support for multiple deployers. 
But this is in fact rejected at the config level by `oneOf` annotations. 
Removing those annotations doesn't solve the problem because then it's the code that applies profiles that's broken.

**Comment by dgageot** [comment]
This feature was actually removed from the beta because it didn't work. Not sure we should reintroduce it though.

**Comment by nkubala** [comment]
I was never really convinced by the implementation we had. I still personally think we should consider doing this either on an artifact level or a "component" or "module" level rather than just deploying everything twice. I'll close this issue and we can discuss somewhere else if/when the time comes.
