### ISSUE TITLE
Add --cleanup to `skaffold run`

### ISSUE THREAD

**Issue by cliffburdick** [GoogleContainerTools/skaffold#1008]
I have a use case where I don't want to redeploy every time there's a source change, but I want the console to be attached after I deploy. As far as I can tell, skaffold run does not attach the console output. skaffold dev does, but it watches for source output. Should I trick skaffold dev into not watching for source changes?

**Comment by cliffburdick** [comment]
@dgageot This isn't *quite* the same. Ctrl+C on --tail doesn't kill the pod when you're done as far as I can tell.

**Comment by dgageot** [comment]
@cliffburdick would you be ok if we add a `--cleanup` flag to `skaffold run`?

**Comment by MarlonGamez** [comment]
This issue is quite old, but I just wanted to update it and say that we should have a fix soon for this in #4601 :)

**Comment by nkubala** [comment]
thinking about this a bit more, I'm not sure this makes a lot of sense. apart from validating that skaffold is configured correctly, `skaffold run --cleanup` creates resources and immediately tears them down, which is basically a noop. it's true that developers who aren't familiar with skaffold/k8s could incur some costs by running skaffold on a project without cleaning up, but since the default value for `cleanup` is false, they'll have to consciously pass that flag when running `skaffold run`, in which case it seems reasonable that they'd know to just run `skaffold dev` instead.

i'm going to close this one for now, but we can reopen if a more motivating use case comes up.
