### ISSUE TITLE
[Proposal] Introduce v1beta1 config + remove ACR builder

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1283]
I propose removing the ACR builder. 

**Reason**: The ACR builder currently doesn't have integration tests, as we don't have the infrastructure to support it yet. Our current thinking around non-Google cloud builder integrations (e.g #1207) is that we will enable the community to contribute them through "a plugin model". This "plugin model" is still unclear - first candidate was the Knative Build CRD (#851) however there are a lot of changes anticipated in that area, so the path is not completely clear yet. 

`v1beta1`: This will introduce a breaking change and we'll need to introduce a new version. As we are planning to go beta soon, this would be a great opportunity to introduce `v1beta1`.

**Comment by dlorenc** [comment]
+1

**Comment by nkubala** [comment]
I'm a +1 on this as well.

I do think that it's important we figure out what the entrypoint is for contributing external "plugin" builders and deployers sooner rather than later, because we shouldn't discourage skaffold usage with other cloud providers. That said, I think this particular change went in a little too hastily so we should roll it back until we decide what our strategy is moving forward.

**Comment by dgageot** [comment]
+1

**Comment by dgageot** [comment]
This'll also close this issue: #1165
