### ISSUE TITLE
Add GIT_COMMIT and DIGEST_HEX to tagPolicy envTemplate

### ISSUE THREAD

**Issue by bholemt** [GoogleContainerTools/skaffold#1318]
Wish to use something like - 
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:dev-{{ printf \"%.8s\" .GIT_COMMIT }}-{{ printf \"%.8s\" .DIGEST_HEX }}"

Sure it can be passed through command line but so can anything else.

Or a tag prefix option in gitCommit would also be great.

**Comment by balopat** [comment]
Thank you for filing the issue, @bholemt, doesn't the [`gitCommit` tagpolicy](
https://github.com/GoogleContainerTools/skaffold/blob/master/examples/annotated-skaffold.yaml#L10) cover your use case?

**Comment by bholemt** [comment]
Would like to have a prefix option. Eg dev-#commitid-sha256-#sha

**Comment by tejal29** [comment]
We can definately expose "GIT_COMMIT" and "DIGEST_HEX" as  built-in variable which you can use  in EnvTagger

**Comment by mekansm** [comment]
Would this cover other template fields (example: buildArgs)?  Currently, we must replicate your logic for gitCommit tag policy in order to inject the GIT_COMMIT + dirty flag into our images.  

Why do we do this?  It makes it easier when someone to reports an issue to track down what version they are seeing it in.  We like to shove it in the footer of a web page/header in our dev and test environments.

**Comment by nkubala** [comment]
I think the idea is we would expose them as process-local environment variables which you could use anywhere.

don't think our team has time to prioritize this one, but contributions are welcome!

**Comment by tstromberg** [comment]
Leaving this open because it seems like a good idea, and would definitely be open to reviewing a PR that implements this.

**Comment by nkubala** [comment]
this should now be possible with the new custom template tagging strategy.
