### ISSUE TITLE
Streaming build context in cluster builds for faster rebuilds in skaffold dev

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1377]
During `skaffold dev` even for moderate sized frontend apps docker rebuilds can be very slow. I mean the large contexts for example due to npm_modules in a react app. I propose creating a streaming context option using Kaniko. This would have to save the resending of the context and instead would only filesync changes to a PV (for example) that Kaniko would use as a starting layer. 
@nkubala @priyawadhwa @dlorenc @dgageot what do you think about the feasibility of this?

**Comment by priyawadhwa** [comment]
I think this could work, when a file change is made we could spin up a pod with an init container and a container. Through the init container we could sync the changed file to the PV, and then the container could run kaniko?

It's would be pretty similar to how the local kaniko builder works right now, except we'd be syncing individual files instead of a tarball of the build context.

**Comment by dgageot** [comment]
Hi everybody, I'm going to close this issue since we don't have the bandwidth to implement it. Feel free to reopen if you think otherwise.
