### ISSUE TITLE
deploys overlap easily with skaffold dev

### ISSUE THREAD

**Issue by matti** [GoogleContainerTools/skaffold#1444]
I think skaffold needs better cleanup logic, because it's often confusing to see logs from previous deploy.

Here is a quick script I wrote to fix my specific use. It ensures that all pods are deleted.

```
#!/usr/bin/env sh
set -e

Cleanup() {
  set +e
    kubectl delete pod --all --force --grace-period 0
  set -e
  echo "Cleanup done"
}

Shutdown() {
  echo "Shutdown started"
  set +e
    killall skaffold
  set -e
  Cleanup
  echo "Shtudown done"
  exit
}
trap Shutdown INT TERM

Watchdog() {
  watch -d -t -g ls -lR >/dev/null 2>/dev/null
  killall skaffold
}

while true; do
  Cleanup

  Watchdog &
  skaffold dev --trigger manual
done
```

**Comment by balopat** [comment]
Hi @matti does this happen even when you shutdown skaffold cleanly? Unclean shutdowns can result in the cleanup hook not having the chance to cleanup. In this case `skaffold delete` should help too. Have you tried that?

**Comment by matti** [comment]
umm, yeah - but the problem I'm describing is that after skaffold has noticed changes it should not show logs from old containers.

**Comment by priyawadhwa** [comment]
hey @matti unfortunately our pod selector will sometimes include old pods until they are completely deleted, and so those logs will show for a few seconds until the pod is terminated. This is expected behavior.

I'm going to close this issue, but if this isn't the issue you are facing please comment or reopen. Thanks!
