### ISSUE TITLE
Default repository alternative implementation

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1545]
I'd like to talk about an alternative implementation for `default repository` handling.

I currently don't use that feature for multiple reasons:
 + It's a piece of configuration that's not visible in the `skaffold.yaml` or `annotated-skaffold.yaml`. This makes it hard to discover and explain.
 + If I use it with Skaffold examples, it gives me silly images names like `gcr.io/dga-demo/gcr.io/k8s-skaffold/skaffold-example` (this could be fixed, no matter what)
 + It should be possible to produce a `skaffold.yaml` that both works great with or without a default-repo. It's currently not possible.

Here's what I'd like to see:
+ The `default-repo` or **Default Registry** could be configured in a `skaffold.yaml`. In which case it would be a prefix added to all the image names in that file.
+ `skaffold --default-repo` would override this value
+ skaffold global config could also override this setting the way it does now.
+ The parameter would be added to a new section of the `skaffold.yaml`. All the parameters of this new section could be overridden by a flag or a global config.
+ We should stop treating `gcr.io` is any special way and just concatenate the default repo to every image name.

**Comment by dlorenc** [comment]
I'd still like to see a way for skaffold to auto-assume a default repo so things "just work" for most users without them having to change anything in a skaffold.yaml.

**Comment by corneliusweig** [comment]
I'd also like to raise why the substitution logic currently replaces `/` with `_`. This seems to be a bit restrictive, because it means that images cannot be organized in folders when using the substitution mechanism.

**Comment by nkubala** [comment]
this issue is getting very old, but there's definitely still some improvement work to be done here. dropping the priority to p2.

**Comment by MarlonGamez** [comment]
This isn't currently prioritized by the team, but I think that this would a good change that a beginner contributor could get their hands on. Going to add appropriate labels.

**Comment by Gikkman** [comment]
Our company has run into issues with the `default-repo` too, since we organize images in different sub-projects in our artifactory (e.g. `infrastructure/nginx`, `my-team/new-app`, `other-team/their-app`) and then have one registry for prod/stg and one for dev. Since this flag replaces `/ ` with `_`, we can't just write out e.g. `my-team/new-app` as the image name. Instead, we have to rely on patching the image name everywhere to contain the entire repository address, which has lead to a few failed deployments through the months.

Would it be possible to maybe reduce the size of this problem, to try to tackle just the `/` to `_` escaping separately, or maybe control the behavior via a flag?

**Comment by tejal29** [comment]
Thanks @Gikkman This has been on team's radar for long.  
We do choose `concat` strategy for `gcr` and google artifactory registry urls.
It would be easy to extend this [behavior](https://github.com/GoogleContainerTools/skaffold/blob/ea2b8b576112e49fc066291c100228ce61b4588a/pkg/skaffold/docker/default_repo.go#L75) to be default via flag or globlal config 


Please feel free to contribute.
