### ISSUE TITLE
Create a simple docs test for Yaml reference page

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1909]
I just ran into an issue that I luckily caught manually, but would be nice to detect if it happens: a schema issue caused a javascript error in `docs/content/en/docs/references/yaml/main.js` and that caused an empty page - but no tests were broken!  

I would want to see a test that runs with check-docs - querying the http://localhost:1313/docs/references/yaml/ page should return some specific content.

**Comment by corneliusweig** [comment]
I don't think this check can be part of check-docs. The page generates the table from the `schema.json`, so that cURLing it will be useless. In addition, the table rendering is not complete when doing a simple request with [headless chrome](https://developers.google.com/web/updates/2017/04/headless-chrome).

I think the most reliable way to test this, is to write some javascript tests which take the real schema.json as input.

**Comment by dgageot** [comment]
@balopat @corneliusweig I have a prototype working with https://github.com/chromedp/chromedp. The idea is to run the docs site and ask chrome headless to grab the page and wait until some content is displayed.

**Comment by balopat** [comment]
That sounds awesome. Would be great to add it in - do you want to demo it on a Skaffold office hour?

**Comment by tstromberg** [comment]
Marking as stale, since it's been a while and does not appear to be on the teams priority radar. Feel free to reopen if you disagree.
