### ISSUE TITLE
Revert plugin infrastructure

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1988]
After lengthy discussions we decided to move away from the plugin model for builders and rather enable a lightweight extension model. 

The cost of the a full-blown plugin model in terms of complexity, loss of functionality (schemas) and developer time would in the end benefit only a small fraction of potential and current skaffold users. We will support a selected few builders that are coming down the line, and most likely we won't take external contributions for most of the builders out there, only the ones that align well strategically with covering most of our targeted users. 

An escape hatch - lightweight extension model is still going to be provided for users that are in need for specific image builders. The details of that are going to be worked out in the next couple of days. 

This issue is to remove the hashicorp go-plugin related infrastructure. I will close all the plugin related issues as well referring to this decision.

**Comment by priyawadhwa** [comment]
Plan for reverting code:

- [ ] remove bazel plugin because it's pretty self contained #1989 
- [ ] remove docker plugin, which will remove almost all of the plugin code since GCB is tied to it as well
- [ ] remove executionEnvironment and plugin fields from config, will require a config change
- [ ] make sure any additional cleanup is done (constants, documentation, integration test cases, etc)

**Comment by priyawadhwa** [comment]
This is done now, closing.
