### ISSUE TITLE
Not all flags should be set from environment Variables.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#2031]
Currently in code, skaffold visits all flags registered for a command and then checks if a corresponding env variable is set for the flag name [here](https://github.com/GoogleContainerTools/skaffold/blob/782c111a2ab1347a99e07cc8093f090f2b5517d8/cmd/skaffold/app/cmd/cmd.go#L124)

This is incorrect for flags which accept multiple values. 
E.g.:
For `insecure-registry`, users might set their env variable to 
```
SKAFFOLD_INSECURE_REGISTRY="localhost:80/test,someotherhost:80/test"
```

In this case, we will incorrectly set the value to this "localhost:80/test,someotherhost:80/test"

Other issue with this is: flags like `--rpc-port` should probably not have the same constant value.

### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. ...
2. ...

**Comment by corneliusweig** [comment]
Is it really more important to avoid possible user errors, than staying consistent? I love the current state where it is really consistent that all flags can be set by env vars. This is also important for the IDE integration, because you cannot add flags but it will be possible to set env vars (https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2497).

As to the `--insecure-registry` flag: I've stumbled over this exact same problem. I think we should instead fix setting multiple values via an env vars, because also the `--label`, `--profile`, and `--artifact` flags have the same problem.

**Comment by corneliusweig** [comment]
@tejal29 So I fixed the multi-valued env vars problem (see above). Maybe this one should be closed if #2032 is accepted?

**Comment by nkubala** [comment]
I definitely think we should prioritize consistency over trying to steer users away from error here. differences in the way flags are set would not be immediately obvious to users, and would probably lead to confusing results. with #2032 the resulting values consumed by skaffold should be pretty clear when set through multiple vehicles, so I think this issue can be closed.

**Comment by tejal29** [comment]
re-opening this. 
I feel by allowing users to set any flag value via env is a error prone. There should be whitelist of options which could be set via env.

**Comment by corneliusweig** [comment]
@tejal29 maybe this can be resolved by better documentation?
I think it is quite valuable to have env variables for all flags for the IDE integration (because env flags can be provided to skaffold, whereas custom flags cannot). Besides, I don't know of any issues, where users ran into problems with env vars.

**Comment by tejal29** [comment]
ah, i just looked in the issue you pointed out. 
Makes sense!
