### ISSUE TITLE
Is there a way to deploy to files?

### ISSUE THREAD

**Issue by lucasmpr** [GoogleContainerTools/skaffold#2161]
I'm trying to create a CI/CD flow with kubernetes and skaffold. I still dont have a way to have the history of the deployed versions, or do a simple callback. 

What I was thinking about  is to export the tagged yaml generated by skaffold deploy to commit them and finally trigger the CD process.

Is there a way?

**Comment by balopat** [comment]
Thanks for opening this @lucasmpr - it might be interesting to explore this direction - it seems to me that it would require a `skaffold render` phase rather than `deploy` to file - as deploy is implicitly a "render" & "kubectl apply" operation. If there is a lot of interest we could expose this - for `helm` we could use [`helm template`](https://helm.sh/docs/helm/#helm-template) for the final deployables.

**Comment by lucasmpr** [comment]
#1937 has a similar question.

I don't see another way to do GitOps inside skaffold without this step. 

I can try to build something if you need me.

**Comment by reegnz** [comment]
I would welcome for skaffold to just dump the patched manifests without doing anything with it.
I am doing GitOps with ArgoCD and I would definitely want skaffold to just dump the  patched manifests somewhere predefined, so that I can commit them automatically if the version matches a given rule.

I'd like to achieve something similar to what (https://github.com/weaveworks/flux)[flux] does with watching docker repos, but instead of watching images and only patching images, I want updates to the manifests propagated to the deploy repo.

**Comment by cmeury** [comment]
Just ran into the same issue, would also love to see an option to only render manifests. Or move towards Helm v3 which is tiller-less anyway?

**Comment by wstrange** [comment]
Would also like to see a kustomize manifest output option.  Could be the entire manifest, or optionally, a list of kustomize edit commands to "fix" up the images for deployment?

**Comment by alnr** [comment]
See [this comment](https://github.com/GoogleContainerTools/skaffold/issues/1937#issuecomment-509255138) which comes close to what OP wants, but does not quite work fully yet.

**Comment by strikeout** [comment]
This is super important for tight integration into existing CI/CD pipelines. 
Please implement a render stage or a custom_script deployer (like the build stage already has)

**Comment by balopat** [comment]
We are looking at implementing this feature this quarter for flows where we can.

**Comment by balopat** [comment]
I realized that this was already an issue opened in https://github.com/GoogleContainerTools/skaffold/issues/1187 - closing this - we are going to track it in #1187
