### ISSUE TITLE
Provide mechanism to indicate language runtime type for an artifact

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#2203]
`skaffold debug` currently uses [a set of heuristics](https://github.com/GoogleContainerTools/skaffold/pull/1702) to guess the language runtime used in a container image:

> We guess the runtime technology for an image container by examining the referenced image container configuration, specifically looking at the environment variables and command-line. It turns out that most of the language runtime base images [define a XXXX_VERSION environment variable](https://github.com/GoogleContainerTools/distroless/issues/276#issuecomment-460375014) or use a well-known command-name (`java` or `node` or `nodemon`).

These heuristics fail for Go and C++ programs.  Although Go does have some [runtime environment variables](https://golang.org/pkg/runtime/), they aren't always used.  And these heuristics may result in false-positives for mixed-runtime images.  We need a way to define the language runtime for a particular artifact.

## Proposal

- Allow setting hints via an environment variable: `SKAFFOLD_RUNTIME`?
- Allow providing hints via a container image label/annotation: `skaffold.dev/debug/runtime`
- Allow providing hints via a k8s manifest label/annotation: `skaffold.dev/debug/runtime`
- Allow setting the language runtime type in `skaffold.yaml`:
  ```yaml
  artifacts:
  - image: gcr.io/foo/bar
    runtimeType: go
  ```

**Comment by corneliusweig** [comment]
Sounds like a good idea. Some thoughts:
- An environment variable can only be set once, so for multi-artifact projects with different technologies per artifact, this would fail miserably. If the env variable would be extended to `SKAFFOLD_RUNTIME_<IMAGENAME>` this could work, but I think this is too complicated. In essence, I would not support that setting via env variable (and also via command line for the same reasons)
- The annotation is a good idea and I think Skaffold should add these labels. However, it goes against the usual Skaffold way of expecting those labels to be added in k8s manifests. Usually configuration either comes from `skaffold.yaml` or the command line.
- The last suggestion to put this in `skaffold.yaml` seems the cleanest approach to me. I'm not entirely sure about the config name though. As is, it does not make explicit that this only relevant for debugging and users may get confused. What about `debugRuntime` or `debugType`?

Maybe you should also involve the IDE people here. They may have preferences and ideas how this can best work together with CloudCode.

**Comment by briandealwis** [comment]
Environment variables are on a per-artifact basis (well, per-container really), so that's not really a concern.  `skaffold debug` should allow any of these approaches so that the developer can do whatever is most convenient for them; the recommended practice though is the skaffold.yaml.

**Comment by etanshaul** [comment]
> Environment variables are on a per-artifact basis (well, per-container really), so that's not really a concern
I think I also interpreted it like @corneliusweig, where the env var would be set on the Skaffold process. Whereas I think here you mean to set it in the k8s config.

**Comment by etanshaul** [comment]
My intuition is that adding this to `skaffold.yaml` makes most sense as well. This is a configuration option specifically intended for Skaffold, and as such, seems like it belongs in the skaffold configuration.

The easiest solution from an IDE perspective would be to have this as a command flag - but given that it needs to be on a per artifact basis, it's probably infeasible?

@iantalarico for comment as well

**Comment by briandealwis** [comment]
Ah sorry.  I meant either [Dockerfile ENV](https://docs.docker.com/engine/reference/builder/#env) or [k8s container env](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#container-v1-core) flags.

I think a command-line flag can be done, and `debug` needs to support something like that for #2184.  I think specifying a path to the artifact should be sufficient:
```
skaffold debug --type /path/to/artifact=go --type /path/to/other/artifact=c++
```

**Comment by etanshaul** [comment]
ah right. that would work. Just to be explicit event though it was probably clear - this would be the easiest option from the IDE perspective because it wouldn't involve modifying any configuration. Instead we could just pass this "runtime type" at command execution time.

Side question: if a runtime type isn't supplied, _and_ `skaffold debug` fails to do its inference, presumably entire skaffold session won't fail, right? Instead it will just not apply any debug transforms. Similarly it would be nice if this failure to debug was output as part of the enhanced debug event api.

**Comment by briandealwis** [comment]
I haven't looked into how to hook into the events yet, but I figured I'd just return a map of artifact &rarr; debug configuration (runtime-type + debug ports). And indeterminate artifacts would be a null mapping.

**Comment by corneliusweig** [comment]
> Ah sorry. I meant either [Dockerfile ENV](https://docs.docker.com/engine/reference/builder/#env) or [k8s container env](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#container-v1-core) flags.

That makes perfectly sense.

I think the standard way to identify an artifact in Skaffold is to use the image name and not the path. That has the advantage of being stable wrt. refactorings (unless the image name is changed :/), so what do you think about:
```
skaffold debug --type gcr.io/skaffold/getting-started=go
```

**Comment by corneliusweig** [comment]
While looking at #2184 I just had another idea how the runtime type could be specified elegantly on the cmdline: the switch to enable debugging could also be used to specify the runtime
```
skaffold debug --debug-artifact gcr.io/skaffold/getting-started=go
```
This would save typing/pasting of the image name and is equally expressive (the separator may be up to debate).

One drawback: it will no longer be possible to specify the runtime without restricting the debugged artifacts.

**Comment by iantalarico** [comment]
Jumping in a little late but I agree that passing the information to skaffold would be the easiest from the IDE side.

**Comment by briandealwis** [comment]
You're right @corneliusweig the image tag is better since several artifacts can be mapped to the same location, as happens with Jib multi-module projects.

**Comment by etanshaul** [comment]
using the image tag should work fine from the IDE perspective.

**Comment by etanshaul** [comment]
> I haven't looked into how to hook into the events yet, but I figured I'd just return a map of artifact → debug configuration (runtime-type + debug ports). And indeterminate artifacts would be a null mapping.

That works. Having it return a null mapping, but still have the artifact information, will be helpful for the client.

**Comment by balopat** [comment]
We need to enrich the heuristics in runtimes/artifacts so that skaffold can detect what language runtime an artifact is using, so that `skaffold debug` can do the right "magic" of rewriting the manifests. 

Another way I would phrase this: With this feature set we start a set of standard mechanisms to make a runtime image Skaffold compatible? 

> Allow setting hints via an environment variable: SKAFFOLD_RUNTIME?

+1 on env vars. I think this is a natural fit with the rest of the heuristics and eventually can become a standard thing across Dockerhub images as well, if we wanted to make an effort - we could raise a PR for all of them to include this ;) 

> Allow providing hints via a container image label/annotation: skaffold.dev/debug/runtime

I'm okay with this, but not convinced. One benefit I see, is that the Dockerfile doesn't have to change for the image. But that also means that if we'd ever inject a skaffold utility inside the container, it wouldn't know about the runtime. What is your thinking around the benefits for this mechanism? 

> Allow providing hints via a k8s manifest label/annotation: skaffold.dev/debug/runtime

I wouldn't expose this as part of the manifests. It is redundant, and also kind-of-in-the-middle: We are talking about images to be connected to skaffold. It is redundant because with env vars you can simulate this even in a pod spec. We let skaffold know in the artifact config directly. 

> Allow setting the language runtime type in skaffold.yaml:

Big plus on this one. As I mentioned, this feature connects images to skaffold. Having the ability to define  it/override it in skaffold.yaml makes sense to me. 

I'm luke warm on the ability to pass it in as a flag - it would be useful for IDEs as then you could override things without touching the yaml - however the IDE would need to store it somewhere...so why not just create a debug profile that has the override?

**Comment by balopat** [comment]
A crazy idea: we could have a set of known image names -> runtimes mapping themselves listed explicitly somewhere as well as another source of heuristics.

**Comment by briandealwis** [comment]
This could be a good way to allow specifying an Alpine-based Delve image (GoogleContainerTools/container-debug-support#30).

**Comment by jkleckner** [comment]
It also seems to me that `skaffold.yaml` would be the right place to annotate the runtime explicitly.

**Comment by briandealwis** [comment]
I'm going to add an `runtimes` attribute to artifacts.  Multiple runtimes allows expressing needs like Go-on-alpine (`runtimes: ["go","alpine"]`).  It turns out I need this for Buildpacks support.

**Comment by eikemeier** [comment]
> I'm going to add an `runtimes` attribute to artifacts. Multiple runtimes allows expressing needs like Go-on-alpine (`runtimes: ["go","alpine"]`). It turns out I need this for Buildpacks support.

v2beta2 is published, but is identical to v2beta1 :grin:. Will this be in v2beta3?

**Comment by nkubala** [comment]
@eikemeier 🤦 

yes hopefully so. the [PR](https://github.com/GoogleContainerTools/skaffold/pull/3943) is still in draft, but we don't have any other config changes in the works to my knowledge, so it *should* go out with the next config bump. however, that isn't tied to our next release necessarily. in any case, stay tuned and we'll get this shipped ASAP.

**Comment by tejal29** [comment]
@briandealwis going through quarterly scrub and just wanted to make sure if this is still a priority.

**Comment by anthonyalayo** [comment]
I'm using Amazon Corretto along with a maven wrapper command, and unfortunately this also fails the heuristics for determining a java runtime. Being able to explicitly tell skaffold what we want would be fantastic.

As a workaround, would it be possible for skaffold to key off of `JAVA_HOME` instead of `JAVA_VERSION`?
[Original PR here](https://github.com/GoogleContainerTools/skaffold/pull/1702/files#diff-eb60a283aae42aa5a16efafe00da02610e21b884915bbbedac3562349da5d787R43)

Since openjdk images are officially deprecated, it would be nice for this to work with others.

**Comment by anthonyalayo** [comment]
Another issue that I hit that would be solved with the support here would be this:
https://devpress.csdn.net/cloudnative/63055d527e6682346619e0d7.html

Running with the java spring boot plugin is quite common in order to get hot class reloading. The current process for skaffold (and cloud code) to recognize automatically adding debug ports conflicts with this setup.

**Comment by anthonyalayo** [comment]
Another issue I hit that would be solved with the support here would be this:
https://stackoverflow.com/questions/72348615/how-to-debug-a-jdk-docker-container-in-intellij-idea

Running with the java spring boot plugin is quite common in order to get hot class reloading. The current process for skaffold to automatically add debug port forwarding conflicts with this setup.

I'm not sure how much this crosses the boundary between skaffold and cloud code, but in order to use the extension, I had to do the following workaround:
```
ENV JAVA_VERSION=11.0.16
CMD JAVA_TOOL_OPTIONS="" ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug $JAVA_TOOL_OPTIONS"
```

Where I had to
1. Add the `JAVA_VERSION` environment variable to get ports automatically added to manifests
2. Blank out the automatically injected `JAVA_TOOL_OPTIONS` for the run command
3. Add `JAVA_TOOL_OPTIONS` into spring boot's plugin arguments

If there was a flag I could add to the skaffold.yaml file that says "add java debug ports", I could replace these three steps with just one.
