### ISSUE TITLE
Watch for helm chart changes

### ISSUE THREAD

**Issue by gmorse81** [GoogleContainerTools/skaffold#235]
Skaffold currently only watches for changes happening within a Dockerfile. Since Skaffold already supports helm deployments, it would be great if the helm chart location could be identified as an artifact so if the chart templates are changed, it would kick off a new build. 

I am currently working around this by copying the chart itself to the docker image. obviously not a permanent solution since this bloats the final docker image.

**Comment by r2d4** [comment]
Yes, we need this for all deployers.

The way I envision this working is that the Deploy interface now has another function

```golang
(*Deployer) Dependencies() ([]string, error)
```

The deployers would be responsible for using the deploy config to output a list of dependencies that should be watched by skaffold.

Of course, this relies on some work that I'll be doing to decouple watch from artifacts, since only artifacts can be watched right now.

**Comment by gmorse81** [comment]
Awesome. Yes that would be great. 

Great work on this project BTW. it's already doing great things for my local dev setup.

**Comment by r2d4** [comment]
Fixed by #765
