### ISSUE TITLE
Enable filesync with debug

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#2351]
`debug` currently disables the Skaffold watcher to prevent Skaffold from redeploying artifacts on file changes: having a debug session ripped out when in progress is a suboptimal user experience!  And many runtimes support installing changes, normally handled by the IDE.

But a side-effect is that this also disables the filesync functionality.  We should be able to forego artifact redeployment while still supporting filesync.

**Comment by corneliusweig** [comment]
That sounds good, however it can also be confusing: Sync has to be configured by supplying sync patterns. If a file gets changed which does not match any of the sync patterns, the container is usually rebuilt. Now if some changes get applied (via sync in debug-mode) and others are not (because they would require a rebuild in debug-mode), this can be a bit confusing.
Overall, I'm not sure if we do our users a favor, if sync is enabled during debugging.

**Comment by briandealwis** [comment]
It seems some language runtimes, like Python, do not support a debugger-controlled hot-swap capability.  VS Code and the Debug Adapter Protocol [do not support installing code-changes either](https://github.com/microsoft/vscode/issues/6930#issuecomment-420798612).

**Comment by corneliusweig** [comment]
@briandealwis Do I understand you correctly, that this also speaks against enabling sync in debug mode?

**Comment by briandealwis** [comment]
The opposite: Python's pydevd has some support for reloading changes from disk (`pydev_reload`). Haven't tried to figure out how to integrate it though.

**Comment by tstromberg** [comment]
Is this still an issue?

**Comment by briandealwis** [comment]
Yes.
