### ISSUE TITLE
(Feature request) Support docker buildx build

### ISSUE THREAD

**Issue by hach-que** [GoogleContainerTools/skaffold#2475]
We're currently using skaffold with buildkit enabled. We found a bug in buildkit (https://github.com/moby/buildkit/issues/1072#issuecomment-511468942) and they've since fixed it, but now we need to use the new version of buildkit in our infrastructure.

The recommended way of using a newer version of buildkit than the one `DOCKER_BUILDKIT=1` provides is docker buildx: https://github.com/docker/buildx

We use skaffold for our builds, so in order to use buildx, we need skaffold to be able to use it as an alternative to `docker build`.

**Comment by hach-que** [comment]
Closing this for now as apparently you can use newer versions of Buildkit by just using the `# syntax` feature: https://github.com/moby/buildkit/issues/1072#issuecomment-511487993

**Comment by AndiDog** [comment]
@balopat @nkubala Mind reopening this? I see huge benefits from support buildx and its `--cache-to` feature: as opposed to plain `DOCKER_BUILDKIT=1` execution, buildx can [upload the cache](https://github.com/moby/buildkit#export-cache) for all parts of a multi-stage build and would therefore save lots of time (and the environment).

**Comment by no1melman** [comment]
This would be great to re-open for that exact issue above - we've tested using `docker buildx build` using the caching and it works a treat, it would shave literally hours off of our builds and would be a massive boon to our work

**Comment by briandealwis** [comment]
So you can configure Docker so that `docker build` [uses buildx by default](https://docs.docker.com/buildx/working-with-buildx/#set-buildx-as-the-default-builder) with `docker buildx install`.  If you combine that with [`useDockerCLI: true`](https://skaffold.dev/docs/references/yaml/#build-local-useDockerCLI) then you'll be using `buildx`.

Adding support for `--cache-to` is a bit more difficult.  Docker labels `buildx` as [an experimental feature](https://docs.docker.com/buildx/working-with-buildx/#set-buildx-as-the-default-builder) that may change without notice.  So I'm a bit leery about adding adding dedicated fields for builder options that may be changed, renamed, or removed without notice.  Perhaps we should incorporate the Kaniko builder's now-removed `AdditionalFlags`.

**Comment by no1melman** [comment]
I think any way we can add extensibility to the API so we can leverage these features would be great. `AdditionalFlags` sounds great, I understand not creating specialised fields.

**Comment by tejal29** [comment]
Though this is a reasonable feature request, the team does not have bandwidth to take a look at this at this moment. 
Would love help from community to get this done. 
If anyone is interested, please comment on the issue  or better submit a [design proposal ](https://github.com/GoogleContainerTools/skaffold/blob/master/docs/design_proposals/design-proposal-template.md)and the team can help you getting this in.
