### ISSUE TITLE
Skaffold dev not picking up remote kustomization.yml

### ISSUE THREAD

**Issue by benjamin-bergia** [GoogleContainerTools/skaffold#2581]
### Expected behavior
When running `skaffold run` the kustomization.yml file from my remote repository is used. I would expect `skaffold dev` to behave the same way.

### Actual behavior
Skaffold seem to interpret the path as a local directory path but only in `dev` not in `run`
 
### Information

- Skaffold version: v0.34.1
- Operating system: Fedora 30
- Contents of skaffold.yaml:

```yaml
deploy:
  kustomize:
    path: https://****
```

### Steps to reproduce the behavior

1. `skaffold dev`

**Comment by priyawadhwa** [comment]
Hey @benjamin-bergia thanks for submitting this bug. It looks like the bug is in the [findKustomizationConfig](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/kustomize.go#L222) function, where we only check if the file exists locally. 

It's used when gathering dependencies, and we would basically want to read the remote manifest [here](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/kustomize.go#L170) if one is provided instead of assuming a local manifest. 

Would you be interested in submitting a PR for this?

**Comment by benjamin-bergia** [comment]
Hi @priyawadhwa,

I can have a try. By the way, why is the kustomization.yml read by skaffold instead of just passing the path to kustomize?

**Comment by benjamin-bergia** [comment]
@priyawadhwa  Actually I took a deeper look and I don't think I will be able to fix it.

The parsing seems to fail for newer versions of kustomize (we are using 3.1.0). In addition the test for local or remote files is apparently not working at all, it simply canonicalize anything that is not a relative path including http urls.
One way to solve this would be to use to same lib than kustomize (https://github.com/hashicorp/go-getter).

But all of this is needed only to watch kustomize files. Why not avoiding all the troubles and just passe the path to kustomize directly?

**Comment by jmcclell** [comment]
> Skaffold seem to interpret the path as a local directory path but only in dev not in run

This is because `run` doesn't do any file watching  to check for changes. In `dev` mode, Skaffold traverses the Kustomize configuration starting at the root config under your `deploy` section and generates a list of all files referenced in the config tree. Once it has that list, it can setup file watching on them individually.

Of course, remote Kustomize configs really put a wrench in all of this. You can't add a file system based watch to a remote config. So, the solution I ended up implementing simply *ignores* any file that doesn't exist locally. The logic here  is that we're only looking for these files to watch them for changes, so if the file isn't local skip it. There's no need to attempt to figure out if it's a real remote or, if so, what kind, because Kustomize will do that for us and error if the remote  file doesn't actually exist.

So,  the code you're looking at has a single purpose: gather a list of files to watch. That's it.

@priyawadhwa is right about where the bug is. I forgot to cover the use case where the *root* config is remote.

I'll take a look and see if I can patch this.
