### ISSUE TITLE
Support Source-to-Image for builds

### ISSUE THREAD

**Issue by cliveseldon** [GoogleContainerTools/skaffold#264]
Any plans to support RedHat's [Source-to-Image](https://github.com/openshift/source-to-image) for building images?

**Comment by r2d4** [comment]
At first we're probably going to support builders with some sort of dockerfile/config file since those will cover the most use cases (something like https://github.com/projectatomic/buildah).

In the future as we start to stabilize these APIs, we'd be interested in supporting these higher order source to image buildpacks or builder images.

**Comment by dlorenc** [comment]
This was opened first, but the other one has a bit more discussion.

https://github.com/GoogleContainerTools/skaffold/issues/518

Closing as a dupe.
