### ISSUE TITLE
Enhancement: Add tag to image on skaffold deploy

### ISSUE THREAD

**Issue by Jonathan34** [GoogleContainerTools/skaffold#2872]
Hi,

Context: I have one GCR, three clusters for 3 different environments (dev, staging, prod).

In CI, I build the image using `skaffold build -q > build.out`
-> images are tagged with gitCommitSha.

In CD, I deploy the images using `skaffold deploy -a build.out` using kustomize deploy.
I have an environment variable that tells me what to deploy (DEV, STG, PROD)
-> once deployed to dev: add a tag `dev` to the images
-> once deployed to staging: add a tag `staging` to the images
-> once deployed to prod: add a tag `prod` to the images

I cannot seem to find a way to do that automatically.

The only workaround i can think of is to parse the build.out after `skaffold deploy` succeed, and go one by one set the tags. 

Any better idea or native way of doing that with skaffold?

**Comment by nkubala** [comment]
this could be accomplished in a few ways (neither of which are yet supported in skaffold):
* a post-deploy hook, that on successful deploy just calls `docker tag` on your images and pushes those new tags to a registry. https://github.com/GoogleContainerTools/skaffold/issues/1441
* supporting multiple tagging strategies in a single skaffold run, and allowing users to specify a "custom" tag - in your case would be dependent on your environment variable, but could be switched out based on active profile. https://github.com/GoogleContainerTools/skaffold/issues/1269 and https://github.com/GoogleContainerTools/skaffold/issues/2169

the second option here wouldn't be identical to what you're describing, since the tag would happen *before* the deploy phase (instead of after). would this be sufficient?

it's worth noting that both of these features will likely be implemented at some point in skaffold. since they're both being tracked in separate issues, i'll close this one for now (though feel free to continue the discussion here).
