### ISSUE TITLE
Deprecate the kaniko artifact type

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#3250]
The `cluster` builder should be able to build `docker` artifacts using `kaniko`, without the user having to change the artifact type.

We should move all the `kaniko` configuration to the `cluster` builder.
(flags, buildContext, image, cache, reproducible, skipTLS)

**Comment by balopat** [comment]
I'm not sure I agree with all this. 

1. kaniko is useful to know as the underlying implementation, so the explicit name is good, not sure why we need to deprecate it
2. 
`flags` are kaniko specific. 
`buildContext` - maybe generic enough, but is required `per artifact`
`image` - yes, we could have a builderImage I guess - but that limits the contract to a single image, instead of a pod spec. 
`cache` - is again a very kaniko specific caching setup 
`reproducible` - again very kaniko specific
`skipTLS` - artifact specific - what if you want to mix registries across artifacts? 

3. building a Dockerfile in cluster could be done with Docker itself with the right elevated pod spec. Or with Buildah, which all have their own flags. How would you represent that? 

I think artifact type is a bit of a misnomer - it is the "build tool" that we configure per artifact.

**Comment by dgageot** [comment]
I agree with your points. I still find it complicated to change the artifact type to build a Dockerfile on a cluster though

**Comment by balopat** [comment]
Cluster does not seem like the right place for docker/kaniko specific things. The builder needs to be artifact independent. 

I agree that switching the type can better. The complication is between translating docker settings to kaniko settings: we could have an abstraction over docker and kaniko settings for the translateable subset - and have the option for tool specifics that just won't translate. This way for most cases we could make the switch easier. 

Thus in reality we have 3 layers: 

- build context (applies for all artifacts) 
- artifact type (artifact format typically) 
- build tool (kaniko vs docker vs buildah vs ...) 

We have this issue currently only for Dockerfile as there are multiple tools implementing the same format.
