### ISSUE TITLE
UI for skaffold

### ISSUE THREAD

**Issue by coolpalani** [GoogleContainerTools/skaffold#3309]
If we include UI for skaffold, It would be great to review existing build/deployment history, view logs etc.

**Comment by balopat** [comment]
Thanks for raising this @coolpalani  - yes, I would love to have a UI for skaffold, and yes, this looks like a good candidate for features too!

**Comment by michaelbayday** [comment]
Hi @balopat and @coolpalani, in building a UI/GUI for skaffold, do you have any other requested features for this? My team and I are looking into creating one and would love to share with the community when we're done.

**Comment by tstromberg** [comment]
Adding discuss tag to bring this issue back around for discussion.

@michaelbayday - Sounds wonderful. Do you have anything we can look at yet?

**Comment by MarlonGamez** [comment]
We've recently been discussing skaffold's UI/UX internally, and we're going to prioritize this more in the coming months. 

@michaelbayday, do you have any update on what you've been working on? We'd love to see what your team has done :)

**Comment by gravypod** [comment]
> Hi @balopat and @coolpalani, in building a UI/GUI for skaffold, do you have any other requested features for this? My team and I are looking into creating one and would love to share with the community when we're done.

@michaelbayday I was wondering what functions you would be targeting for this UI? If you're looking for inspiration I think https://tilt.dev/ may be a great source.

**Comment by michaelbayday** [comment]
We ended up running into issues with the rest API and decided to not build a tool. If anyone decides to get started, I'm happy to contribute.

**Comment by briandealwis** [comment]
@michaelbayday would you be able to open an issue around the REST API?

**Comment by gravypod** [comment]
If there's more active development in this is there a slack or discord
where everyone could get together to follow up on projects and ideas?

**Comment by briandealwis** [comment]
We have the [#skaffold channel](https://kubernetes.slack.com/messages/CABQMSZA6/) on the Kubernetes Slack.

**Comment by nkubala** [comment]
we're not currently working on this, for a few reasons:
* we've been focusing more heavily on UX - things like cutting down build logs, making sure error messages are clear, etc. I'd argue that without a good fundamental user experience, making a great UI is difficult.
* since we already have the Cloud Code IDEs as a frontend, we've been treating that as a "UI" in front of skaffold for the time being.
* there are conversations circling around about how to separate "backend" vs "frontend" concerns in skaffold itself. it's not clear what that will look like, but one thing that is clear is that the implications of this w.r.t. a UI in front of skaffold would be so great that it probably doesn't make sense to try and work on this at the moment.

all of that said, in the future this is definitely still on the table. after we've sorted out the prerequisite work (in a few months likely) we should pick this conversation back up.

**Comment by tejal29** [comment]
We the current priorities and much richer UI with new Cloud Code logging experience, team has decided we are not going to work on this.
