### ISSUE TITLE
[Feature Request] activate profiles based on other profiles

### ISSUE THREAD

**Issue by martinhoefling** [GoogleContainerTools/skaffold#3385]
It would be great to be able to activate profiles based on the activation / selection of other profiles. The use case is as follows:
The development setup is composed of a base profile with a set of images / k8s resources. In addition, there are more components that are patched in (added) by activation

- database (default profile)
- app1
- app2
- monitoring
- auth-mock
- mailserver-mock
- auth
...
- dev-default
- dev-performance
- dev-auth

The default profile contains just the database. The usual development profile "dev-default" would require database,app1,app2,auth-mock but not monitoring. While multiple profiles can be specified on the command line via `-p app1,app2,auth-mock`, it would be great to have an alias for the different combinations.

I see two ways to specify those dependencies: 

- activating a profile if another profile is active: That would fit into the current activations, e.g. by adding `- profile: dev-default` in the activations secrtion
- specifying the profiles each profile activates, e.g. by adding a property `activates`:
```
    activates:
        - app1
        - app2
        - ...
```

or 

```
   includes:
     - app1
     - app2
```

Both options would profit from recursing, until no new profiles are added. What are your thoughts?

**Comment by martinhoefling** [comment]
I had a short chat with @corneliusweig 
Activations are probably not the right solution, as they are combined via AND. One other idea I will explore is to use kustomize to compose skaffold profiles. Apart from that, aliases would be sufficient, if nesting (e.g. via includes) is an issue.

**Comment by corneliusweig** [comment]
Yeah, my major concern about activating profile B, when profile A becomes active is that it gives rise to activation chains (think A -> B -> C -> D -> ...). This would become quite difficult to reason about, and thus hard to maintain for users.


---

I think what Skaffold really needs is a better way to structure profiles. Here we could improve the kustomize integration in Skaffold and use it to organize the `skaffold.yaml` file as well. In other words, it make sense to support a `--kustomize` / `-k` flag like kubectl does. This can be used instead of `-f` for complex projects. Nested profiles could then be well organized in folders with bases and overlays, making it much more manageable.

**Comment by martinhoefling** [comment]
The -k flag and the use of kustomize would also enable to use strategicMergePatch instead of JSONPatch. In terms of composability, strategicMergePatch has a much better readability IMHO.

**Comment by balopat** [comment]
This came up before: https://github.com/GoogleContainerTools/skaffold/issues/2542
And we see more and more people using more and more complex configs. I agree that a kustomize based approach would be interesting to explore!

**Comment by aaron-prindle** [comment]
This functionality was added with the `activeProfiles.activatedBy` field:
https://skaffold.dev/docs/references/yaml/#requires-activeProfiles-activatedBy

example usage
```
apiVersion: skaffold/v2beta11
kind: Config
metadata:
    name: cfg
requires:
  - path: ./path/to/required/skaffold.yaml
    configs: [cfg1, cfg2]                 
    activeProfiles:                                     
     - name: profile1                               
       activatedBy: [profile2, profile3] 
```

Additionally we have on our 2023 roadmap to add support using more supporting and documenting how to use more general yaml configuration tools (eg: kustomize) with skaffold.yaml so that profiles aren't bespoke but treated more like normal yaml config.  Closing this issues (fixed) as `activatedBy` I believe solves this issue IIUC

**Comment by aaron-prindle** [comment]
@gsquared94 to verify this issue should be closed.  If not, please re-open
