### ISSUE TITLE
Skaffold YAML reference page broken

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#3618]
The [skaffold.yaml reference page](https://skaffold.dev/docs/references/yaml/) is broken.  It appears to be related to the update of lit-html in #3466

The code is breaking at line 110:
https://github.com/GoogleContainerTools/skaffold/blob/650ed4ba0c8992421f27e8aee3561ebad8bddf2a/docs/content/en/docs/references/yaml/main.js#L114-L116

`value` is `"."` from the `default` value of the `KustomizeDeploy`'s `paths` property, which is defined as an array of strings.

https://github.com/GoogleContainerTools/skaffold/blob/650ed4ba0c8992421f27e8aee3561ebad8bddf2a/docs/content/en/schemas/v2alpha3.json#L1602-L1610

And sure enough, `"."` isn't an array of strings.

But this `default` hasn't changed in ages, so it must be the lit-html.  What's puzzling is why this error didn't show up during testing of #3466?

**Comment by balopat** [comment]
Thank you for the analysis, @briandealwis! There was a kustomize change (https://github.com/GoogleContainerTools/skaffold/pull/3585) that went in _after_ the lit-html change that changed the type of kustomize paths to array of strings from string. I believe the issue is with the default value setting there.
