### ISSUE TITLE
Skaffold json-schema's BuildConfig includes multiple sets of properties

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#3748]
### Actual behavior

Skaffold's schema's `BuildConfig` and `DeployConfig` seem to include 4 copies of their properties within an `anyOf`.  As a result, VS Code shows 4 possible schemas.

```console
$ schema get skaffold/v2alpha3  2>&1 | $PAGER
[...]
    "BuildConfig": {
      "anyOf": [
        {
          "properties": {
            "artifacts": {
[...]
       },
        {
          "properties": {
            "artifacts": {
[...]
        },
        {
          "properties": {
            "artifacts": {
[...]
        },
        {
          "properties": {
            "artifacts": {
[...]
```
### Expected behavior

There should be a single set of properties and no `anyOf`.

### Information

- Skaffold version: 1.0.1 and HEAD

### Steps to reproduce the behavior

`skaffold schema get skaffold/v2alpha3`

**Comment by briandealwis** [comment]
Oddly the DeployConfig's _prior to v2alpha2_ also suffered from similar problems.  Since v2alpha2, they present fine.

In v2alpha1, I notice the subcomponents use a [`yamltags:"oneOf=deploy"`](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/v2alpha1/config.go#L383) style of back-reference?  These are not present in [v2alpha2](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/v2alpha2/config.go#L376).

I wonder if it's worth retrofitting the definition changes to at least v1?  Or maybe we should move to v2 more quickly.

**Comment by dgageot** [comment]
There are two things here:
 + With v2alpha2, Skaffold started supporting multiple deployers. So it's a good things that `yamltags:"oneOf=deploy"` are gone now and a good thing that they were there before.
 + It's also a good thing that we use `anyOf` in the json schema instead of `oneOf`. Those have a different meaning than in our `yamltags` annotations.

Let's say a `field` can take two optional properties `name` and `context` and a third one that is either `docker` or `jib` but not both. The schema could be:

```
"field":{
  anyOf: [
    {
      "properties": { "name":{}, "context":{}, "docker":{}},
      "additionalProperties": false
    },
    {
      "properties": { "name":{}, "context":{}, "jib": {}},
      "additionalProperties": false
    }
  ]
}
```

If we used `oneOf` instead of `anyOf`, the schema would be unable to validate a `field` that has just a `name` because the two options would match that and `oneOf` requires only one matching option.

Either something changed on the VSCode side or we never realized there was an issue in the first place.

**Comment by briandealwis** [comment]
Oh, this makes sense.
