### ISSUE TITLE
status-check: breaks if user does not have access to list deployments at cluster scope

### ISSUE THREAD

**Issue by msirang** [GoogleContainerTools/skaffold#3873]
Hi, I just upgraded at the latest version and having issues during the new "**Waiting for deployments to stabilize**" stage. It seems that Skaffold is trying to get infos about resources outside the user's namespace, but I'm not sure. Anyway, it worked perfectly before, with Skaffold v1.5.0.
The only way to make it to work with 1.6.0 version, is turning off the status-check with `--status-check=false` (thanks to @balopat) 

### Expected behavior
The resources should be regularly deployed on OpenShift Online Starter like it happens with Skaffold version 1.5.0

### Actual behavior
The resources are created but suddenly cleaned from the cluster after the "Waiting for deployments to stabilize" stage starts 

### Information

- Skaffold version: v1.6.0
- Operating system: Windows 10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: angu-ui
build:
  artifacts:
  - image: angu-ui
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubeContext: minikube 
  kubectl:
    manifests:
    - K8s-angular-ui.yaml 

profiles:
- name: openshift  
  build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:v1" 
  deploy:
    kubeContext: sirtest/api-us-east-1-starter-openshift-online-com:6443/maurizio.sirangelo 
    kubectl:
      manifests:
      - K8s-openshift-angular-ui.yaml ```

### The logs at the "check out" stage
...
Waiting for deployments to stabilize
time="2020-03-25T11:44:27+01:00" level=debug msg="getting client config for kubeContext: `sirtest/api-us-east-1-starter-openshift-online-com:6443/maurizio.sirangelo`"
Cleaning up...
time="2020-03-25T11:44:28+01:00" level=debug msg="Running command: [kubectl --context sirtest/api-us-east-1-starter-openshift-online-com:6443/maurizio.sirangelo create --dry-run -oyaml -f C:\\Users\\MT3S\\eclipse-workspace-ee2\\oauth2-jwt-angular-app\\K8s-openshift-angular-ui.yaml]"
time="2020-03-25T11:44:29+01:00" level=debug msg="Command output: [apiVersion: v1\nkind: Service\nmetadata:\n  labels:\n    name: angu-ui\n  name: angu-ui\n  namespace: sirtest\nspec:\n  ports:\n  - port: 8090\n    protocol: TCP\n    targetPort: 8090\n  selector:\n    app: angu-ui\n---\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: angu-ui\n  namespace: sirtest\nspec:\n  selector:\n    matchLabels:\n      app: angu-ui\n  strategy:\n    type: Recreate\n  template:\n    metadata:\n      labels:\n        app: angu-ui\n    spec:\n      containers:\n      - image: sirdockerized/angu-ui:v1\n        name: angu-ui\n        ports:\n        - containerPort: 8090\n]"
time="2020-03-25T11:44:30+01:00" level=debug msg="Running command: [kubectl --context sirtest/api-us-east-1-starter-openshift-online-com:6443/maurizio.sirangelo delete --ignore-not-found=true -f -]"
 - service "angu-ui" deleted
 - deployment.apps "angu-ui" deleted
time="2020-03-25T11:44:31+01:00" level=info msg="Cleanup complete in 3.254956s"
time="2020-03-25T11:44:31+01:00" level=fatal msg="exiting dev mode because first deploy failed: could not fetch deployments: could not fetch deployments: deployments.apps is forbidden: User \"maurizio.sirangelo\" cannot list resource \"deployments\" in API group \"apps\" at the cluster scope"

**Comment by jck** [comment]
I have the same issue:

* skaffold 1.5 works fine
* on skaffold 1.6 and 1.7, I get this error:
`FATA[0012] exiting dev mode because first deploy failed: could not fetch deployments: could not fetch deployments: deployments.apps is forbidden: User "engineer:keerthan.jaic-onepeloton.com" cannot list resource "deployments" in API group "apps" at the cluster scope`
* I can succesfully deploy on 1.6 and 1.7 if i use `--status-check=false`

**Comment by coolpalani** [comment]
I'm also facing same issue when I run `skaffold run -p profile` mode.


`00:02:22  Starting deploy...`
`00:02:22   - service/app-service configured`
`00:02:22   - deployment.apps/app-service configured`
`00:02:22  Waiting for deployments to stabilize...`
`00:02:22  Cleaning up...`
`00:02:22   - service "app-service" deleted`
`00:02:22   - deployment.apps "app-service" deleted`
`00:02:22  time="2020-04-11T00:02:22+05:30" level=fatal msg="exiting dev mode because first deploy failed: could not fetch deployments: could not fetch deployments: deployments.apps is forbidden: User \"u-0mi0rnj3pw\" cannot list resource \"deployments\" in API group \"apps\" at the cluster scope"`

It's working if I explicitly pass namespace value in skaffold command instead of specify namespace under profile flags global.

`skaffold run -p profile -n app`

`23:26:27  Starting deploy...`
`23:26:27   - service/app-service configured`
`23:26:27   - deployment.apps/app-service configured`
`23:26:27  Waiting for deployments to stabilize...`
`23:26:28   - app:deployment/app-service: waiting for rollout to finish: 1 old replicas are pending termination...`
`23:26:40   - app:deployment/app-service is ready.`
`23:26:40  Deployments stabilized in 10.66220246s`

**Comment by tstromberg** [comment]
@coolpalani - Interesting discovery. 

@tejal29 - any reason we can't check within the targetted namespace by default?

**Comment by tejal29** [comment]
This must be a bug. Looks like the namespace `""` is passed to status check which causes to api to query resources in all namespaces.

**Comment by thrix** [comment]
We see this also after upgrading from skaffold 1.1, which worked just fine:

```
Starting deploy...
 - service/artemis-api created
 - route.route.openshift.io/artemis-api created
 - deployment.apps/artemis-api created
 - service/artemis-rabbitmq created
 - service/artemis-rabbitmq-management created
 - route.route.openshift.io/artemis-rabbitmq-management created
 - deployment.apps/artemis-rabbitmq created
 - service/artemis-postgres created
 - deployment.apps/artemis-postgres created
 - route.route.openshift.io/artemis-postgres-exporter created
 - service/artemis-postgres-exporter created
 - deployment.apps/artemis-postgres-exporter created
 - deployment.apps/artemis-dispatcher created
 - deployment.apps/artemis-worker created
Waiting for deployments to stabilize...
Cleaning up...
 - service "artemis-api" deleted
 - route.route.openshift.io "artemis-api" deleted
 - deployment.apps "artemis-api" deleted
 - service "artemis-rabbitmq" deleted
 - service "artemis-rabbitmq-management" deleted
 - route.route.openshift.io "artemis-rabbitmq-management" deleted
 - deployment.apps "artemis-rabbitmq" deleted
 - service "artemis-postgres" deleted
 - deployment.apps "artemis-postgres" deleted
 - route.route.openshift.io "artemis-postgres-exporter" deleted
 - service "artemis-postgres-exporter" deleted
 - deployment.apps "artemis-postgres-exporter" deleted
 - deployment.apps "artemis-dispatcher" deleted
 - deployment.apps "artemis-worker" deleted
exiting dev mode because first deploy failed: could not fetch deployments: could not fetch deployments: deployments.apps is forbidden: User "developer" cannot list deployments.apps at the cluster scope: no RBAC policy matched

```

We are using it against minishift ...
