### ISSUE TITLE
Allow subprofiles in profile definitions

### ISSUE THREAD

**Issue by Mister101** [GoogleContainerTools/skaffold#3889]
I have a skaffold.yaml file that builds and deploys "all" of the services I have in a monorepo. Occasionally I'd like to run a single pipeline or a subset of those pipelines.

Ex: `skaffold run` might run the build + deploy pipelines for svc1, svc2, and svc3
Another time I might just want to run the pipelines for svc2 and svc3.

I'm picturing each service having a separate profile, which can be combined in a way, like:
basic-profile: [svc2profile, svc3profile]

Then I could run `skaffold run -p basic-profile` instead of listing the individual profiles.

Maybe this isn't an intended use of profiles, but either way, it would be useful to have some way of composing pipelines in a similar manner.

**Comment by Mister101** [comment]
Yeah something like that would be perfect. Each step could be defined in the yaml, and steps could potentially be defined in terms of other steps in the yaml file as well. This would make things super simple for composing different pipelines to run different configurations.

One other thing that seems related: doing `skaffold dev` would really benefit from this as well. If I have a release that deploys a remote helm chart, then being able to skip that when a file changes in one of my services would be great. So the different steps/pipelines could have different file watches, etc.

**Comment by tstromberg** [comment]
This should be solved using skaffold modules. @balopat to comment.

**Comment by balopat** [comment]
Hi @Mister101, thank you for suggesting this! Indeed we're working on skaffold modules - that is a promised functionality on our roadmap for this year - this will tackle exactly this problem and others: 
- being able to build&deploy a multi-microservice app all in one go 
- being able to build&deploy one or more individual components 

I'm not convinced that profiles should be the vehicle for this because profiles were more meant to represent environment specific customizations, which is a dimension you might want to keep even if you have multiple modules. I will close this issue for now, but we marked it as area/modules so we'll remember your use case when planning. Thank you!

**Comment by balopat** [comment]
Hi @m1o1 - can you comment on http://tinyurl.com/skaffold-modules whether it satisfies your use case? Thank you!

**Comment by m1o1** [comment]
@balopat Sure I'll check it out tonight and comment. Thanks!
