### ISSUE TITLE
status check fails to report startup errors (hangs on CrashLoopBackOff)

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#3909]
In the current state with status-check=true by default, when a pod does not start up and is in a CrashErrorLoop, skaffold just hangs, waiting for the deployment rollout to finish. This worse than having the status-check=false.

**Comment by tstromberg** [comment]
@balopat - should Skaffold displaying an error and wait until the pod recovers, or should it exit early if CrashLoopBackOff is encountered?

**Comment by nkubala** [comment]
in my experience CrashLoopBackOff is unrecoverable until a new image is pushed, so I think skaffold exiting is probably a better UX since it's clear to the user that a change needs to be made. we'd want to be good about the error messaging here though.

**Comment by nkubala** [comment]
closing this since we have application logs being surfaced from the pods now.

**Comment by codeclown** [comment]
I may be doing something wrong, but here's a problem with the current workflow:

1. Running a helm chart via skaffold, everything going great
2. Save a file which triggers skaffold to rebuild image and deploy
3. Last edit to file caused an instant termination of the updated image, so the pod goes to CrashLoopBackOff
4. Skaffold is stuck with the message "waiting for rollout to finish: 1 old replicas are pending termination..."
5. Making further changes to files does not redeploy anymore, Skaffold is stuck in that position and the only way to get the now-fixed image deployed is to restart Skaffold

This can happen quite frequently because it's not too uncommon to save a file which will contain an error or a bug. E.g. you might change a database connection string to see if the new one works, and if it didn't, now you have to restart Skaffold to make any other changes.

I think Skaffold should still listen for changes when in CrashLoopBackOff state.

**Comment by foobarbecue** [comment]
I'm using skaffold to deploy Argo Workflows, and it doesn't really work because two of the deployments experience CrashLoopBackOff during normal setup until the mysql deployment is ready. I've read that this is standard practice for k8s -- rather than make deployments dependent on each other you just let them keep trying to start up. skaffold is exiting thinking these pods have failed when in fact they're just doing normal Argo startup. This is broken and skaffold should re-open this issue and fix it.
