### ISSUE TITLE
skaffold fix should leave comments as-they-are

### ISSUE THREAD

**Issue by shantanugadgil** [GoogleContainerTools/skaffold#3955]
Currently `skaffold fix` gobbles up all comments. This is a feature request to leave the comments in place

### Expected behavior
comment line beginning with `#` should be let alone

### Actual behavior
comments are removed

### Information

- Skaffold version: v1.7.0
- Operating system: Ubuntu 16/18
- Contents of skaffold.yaml: N/A

**Comment by tstromberg** [comment]
This seems like an entirely reasonable request. Thank you for the suggestion!

**Comment by dgageot** [comment]
@tstromberg any idea on how we should do it?

**Comment by dgageot** [comment]
Perhaps this can help: https://github.com/go-yaml/yaml/issues/132

**Comment by tejal29** [comment]
@tvvignesh, i have a PR in works. 
due to time constraint, i could not finish. Is this something you would be interested in completing? I can help ?

**Comment by tvvignesh** [comment]
@tejal29 Hi. Currently working on my startup (that will take 2 more months to complete) since I am working alone. While I can take this up in the future, now might be difficult. Not sure what timeline you have for this.

**Comment by mfoo** [comment]
Was there any more progress on this?

My suggestion would be that instead of using YAML comments, a `comment`, `documentation`, or `description` YAML key could be added to the schema. This way the comments can be linted in the same way that the skaffold file is and any parse/serialise process wouldn't have to worry about keeping documentation (or guessing at which line/chunk of YAML the comment belongs to).

Example:

Now:

```yaml
profiles:
  # This is used for <some situation>
  - name: myprofile
```

Future:

```yaml
profiles:
  - name: myprofile
    documentation: This is used for <some situation>
```
