### ISSUE TITLE
Build and deploy prechecks

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#40]
Add prechecks to both builders and deployers to ensure basic conditions before the pipeline is ran.  This could be implemented as an interface that both Builder and Deployer embed.

Some ideas for prechecks:
* LocalBuilder: Ensure connection to docker daemon
* KubectlDeploy: Ensure connection to cluster, kubectl installed
* HelmDeploy: Ensure connection to cluster, helm installed, (tiller installed?)

Should these prechecks also verify manifest conditions? I think eventually we might want to add some sort of linting of kubernetes resources, and possibly extend that to skaffold resources.

**Comment by shimmerjs** [comment]
This would be awesome.  There are several things we're having to do outside of skaffold at the moment including some bare bones initialization (copying `~/.npmrc` to `.npmrc` so that its available for docker build) as well as things like linting helm charts.  It would be great if there were some way to configure these as prechecks in skaffold directly.

**Comment by tstromberg** [comment]
As this issue has had its 2yr anniversary without much in the way of updates, I'm going to close this now as stale. It's unclear to me whether or not this is as important as it once was given the changes to Skaffold since it was opened.
