### ISSUE TITLE
Opinion about GitOps as an kubernetes operator.

### ISSUE THREAD

**Issue by StarpTech** [GoogleContainerTools/skaffold#4839]
Hi, any opinion about FluxCD/ArgoCD or any other tool which follows the strategy to install a kubernetes operator on the cluster to handle all the stuff you typically do in the CD/CD pipeline?

- checkout repo
- run helm
- sync state

I cannot get used to the idea of managing an application "operator" when we can do it one step ahead. Locally we can even run a dry phase of the entire release to find misconfigurations earlier. I can practice GitOps with skaffold in the same way.

I found out that tools like FluxCD are also very limited. FluxCD allows only one central config repository. That makes it hard to spin up dynamic environments or acting from point of view of a specific repository / team. The fact that you don't need to connect to your cluster is great from a security perspective but in many advanced cases, you still working with the fluxctl (CLI) which requires a connection to your cluster.

I'd like to hear your opinion about that trend and why skaffold has been developed as a high-level client tool.

**Comment by tejal29** [comment]
@StarpTech Thank you for your question.  This is a deep question and i was wondering if it possible for you to come to our next Community office hours to discuss?https://docs.google.com/document/d/1mnCC_fAI3pmg3Vb2nMJyPk8Qtjjuapw_BTyqI_dX7sk/edit#heading=h.whkfbnrrqifx

The next meeting is on Wed 28th at 9:30 am PST.

**Comment by StarpTech** [comment]
Hi @tejal29, thank you. I'll try to participate.

**Comment by briandealwis** [comment]
Or you might want to post to the [`skaffold-users` mailing list](https://groups.google.com/forum/#!forum/skaffold-users).

**Comment by nkubala** [comment]
@StarpTech did you ever get any good responses or examples that might be worth sharing here?

**Comment by StarpTech** [comment]
Hi, @nkubala not yet but I tried both ways. Do you have any concrete questions?

**Comment by nkubala** [comment]
@StarpTech not necessarily, I'm still trying to wrap my head around your question. I think part of it centers around the debate between client-side vs. cluster-side tooling for development, which is very nuanced and is rooted a lot in the type of actions your development workflow is centered around.

for iterative application development, client-side tooling makes sense - you're developing on your local source, building locally, maybe even deploying locally i.e. to minikube. for CI/CD, cluster-side tooling does have a lot of merit, since you're deploying to an actual remote cluster - but in practice, there is often some client that's responsible for triggering many of these actions, even in a GitOps-based workflow (that commit had to be pushed from somewhere). skaffold's approach right now is bridging the gap between local development and passing off applications to the operational side of things: we refer to this as "shifting left".

that said, are there certain changes you'd like to see to the skaffold architecture that would better enable you to integration with CD? this is a space we're definitely exploring, and I'd love to hear any input you have.

**Comment by briandealwis** [comment]
Closing for now; happy to re-open if there are further discussions.
