### ISSUE TITLE
Add status-check option to the skaffold.yaml

### ISSUE THREAD

**Issue by code-is-art** [GoogleContainerTools/skaffold#4904]
Would like to request that status-check be included in the skaffold.yaml for ease of development. I currently updated to the latest version from a very old version and was confused as to why I had to look at my k8s logs to find out what had happened to my pods until I discovered that the current version of skaffold has status-check set to true by default. I believe this is just fine but now I have to type --status-check=false everytime I want to see a crashed pod log when I am running skaffold dev. It would be great if that flag could be included in the skaffold.yaml so that one can implicitly set it for dev and debug.

- Skaffold version: 1.15...
- Operating system: OS X 10.14.6

**Comment by MarlonGamez** [comment]
I think this is pretty reasonable, and seems easy enough to implement. PRs welcome! :)

**Comment by tejal29** [comment]
making triage-party happy!

**Comment by maggieneterval** [comment]
If this issue is still available to be worked on, please feel free to assign me. Thanks!

**Comment by nkubala** [comment]
@maggieneterval feel free to take it!

**Comment by maggieneterval** [comment]
I looked into this a bit and wanted to confirm the intended behavior before submitting a PR.

Existing behavior:

| --status-check flag | healthcheck enabled? |
| --- | --- |
| unset | yes |
| true | yes |
| false | no |

New behavior:

| --status-check flag | StatusCheck in skaffold.yaml | healthcheck enabled? |
| --- | --- | --- |
| unset | false | no |
| true | false | yes |
| false | false | no |
| unset | true | yes |
| true | true | yes |
| false | true | no |

The existing skaffold [healthcheck](https://skaffold.dev/docs/workflows/ci-cd/#waiting-for-skaffold-deployments-using-healthcheck) is enabled by default, and must be explicitly disabled by using the `--status-check=false` flag. If we add a new `StatusCheck` field to the skaffold.yaml, does this mean that running `skaffold fix` should automatically add `StatusCheck: true` to preserve the existing enabled-by-default behavior? Or is there some way I'm missing to distinguish false from unset in the skaffold.yaml? Also just wanted to confirm since I am new to Skaffold that, for a feature that is intended to be on by default, the complexity of having multiple ways to disable it is justified.

Thank you!

**Comment by tejal29** [comment]
@maggieneterval The above approach looks good to me.

**Comment by maggieneterval** [comment]
Hi @tejal29, thanks for the reply! I opened https://github.com/GoogleContainerTools/skaffold/pull/5706.

Upon further investigation, it appears that there is no way to distinguish a true from an unset `--status-check` flag value ([unset defaults to true](https://github.com/GoogleContainerTools/skaffold/blob/master/cmd/skaffold/app/cmd/flags.go#L279)).

Updated new behavior:

| --status-check flag | StatusCheck in skaffold.yaml | healthcheck enabled? |
| --- | --- | --- |
| true (default) | true (default) | yes |
| true (default) | false | no* |
| false | false | no |
| false | true (default) | no |

*The healthcheck will be disabled when the `--status-check` flag is true (or true by default when unset) and the `StatusCheck` field is false. If the behavior were to enable the healthcheck in this case, then users would have no way of disabling the healthcheck without explicitly setting `--status-check=false` (which was the use case for this issue).
