### ISSUE TITLE
Enable Docker BuildKit by default

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#4936]
With Docker Desktop 2.4.0.0, BuildKit is now enabled by default (release notes for [_Docker Desktop for Windows_](https://docs.docker.com/docker-for-windows/release-notes/) and [_Docker Desktop for Mac_](https://docs.docker.com/docker-for-mac/release-notes/)):
> Docker Desktop now enables BuildKit by default after a reset to factory defaults.

If Docker is confident enough in its use, then we should enable it by default too!

**Comment by dfang** [comment]
@briandealwis @tejal29 

i see errors like `buildkit not supported by daemon` in integration tests on my pr,

if buildkit not supported by daemon, fallback to docker apiclient  ?

**Comment by nkubala** [comment]
yeah a while back i tried to figure out how to enable buildkit on the docker daemon in travis, but failed.

i'm fine enabling buildkit by default in skaffold, but we should still keep around the `useBuildKit` field to disable it when we need to.

**Comment by dfang** [comment]
@nkubala how is it going with [enable buildkit on the docker daemon in travis](#4746) ?  without this, integration tests can't pass

**Comment by no1melman** [comment]
By any chance, will any of this included being able to send args to the Buildkit, like using the inline caching and all that

**Comment by gsquared94** [comment]
we've fixed our issues with using BuildKit in our CI. 
I've been trying to think of a way to make this change and get stuck on how `useBuildkit` and `useDockerCLI` flags are intertwined.
`useBuildkit` can be `true` only when `useDockerCLI` is also true since we don't have the implementation for using the BuildKit via Docker API.

The default for `useDockerCLI` is false. So turning on `useBuildkit` by default will also need making `useDockerCLI` true by default. But we need to specially handle the case when `useDockerCLI` is explicitly set to `false` vs unspecified.

Do we really need both flags?
I propose only having `useBuildkit` flag. Since even now in the code, if `useBuildkit` is true then we bypass `useDockerCLI` setting. 

That way if `useBuildkit` is false, then we continue with Docker API approach (`useDockerCLI = false`). This preserves backwards compatibility and keeps the implementation simple.

wdyt @briandealwis

**Comment by gsquared94** [comment]
erreneously closed

**Comment by gsquared94** [comment]
this should now be done.
