### ISSUE TITLE
Publish macOS/arm64 binaries

### ISSUE THREAD

**Issue by tstromberg** [GoogleContainerTools/skaffold#5042]
NOTE: No released version of Go supports macOS/arm64 as of this date, but v1.16 will. https://github.com/golang/go/issues/38485 has some details on how to get started with making builds from the go trunk source code.

We may have to do something about code-signing on macOS/arm64

**Comment by briandealwis** [comment]
Found a Go program, [`makefat`](https://github.com/randall77/makefat), for producing multi-arch ("fat") binaries for macOS/Darwin.

**Comment by briandealwis** [comment]
Support for darwin/arm64 requires using Go 1.16beta1. We currently build with _cgo_ so that our file-watcher can take advantage of [_rjeczalik/notify_](https://github.com/rjeczalik/notify)'s native capabilities (FSEvents, inotify, etc). We use a Docker-provided cross-building image (https://hub.docker.com/r/dockercore/golang-cross), which includes SDKs (toolchains, headers, and libraries) for Linux, Windows, and macOS.  The included macOS SDKs are for 10.x however, and don't support building for darwin/arm64 which requires an SDK for macOS 11.x.  The legality of including these SDKs is questionable, however.

#5286 is a stop-gap solution that disables using cgo for darwin/arm64 and uses _rjeczalik/notify_'s kqueue support instead.  The kqueue support has worse performance.  But this at least works.

The better (legal) solution requires that we build on macOS and use the right SDKs.  But we should also be signing our builds (#2154).  I think the right solution is to move our builds into Kokoro.  This is a more complex task.

**Comment by briandealwis** [comment]
Error seen on start:
```
$ skaffold dev
ERRO[0000] failure getting variant                       error="getCPUInfo for OS darwin: not implemented"
...
```

This seems to have no effect.
