### ISSUE TITLE
Examples Page Linkrot

### ISSUE THREAD

**Issue by balibebas** [GoogleContainerTools/skaffold#5101]
In `README` find `examples` link, click it and experience the linkrot.

**Comment by IsaacPD** [comment]
Are you referring to https://github.com/GoogleContainerTools/skaffold/blob/master/README.md?

**Comment by balibebas** [comment]
Bit of a strange question. But yes.

**Comment by balibebas** [comment]
Yes but it's not actually link rod it's just an empty examples directory. Pulling it up from the GitHub app on Android says nothing here.

**Comment by IsaacPD** [comment]
Just downloaded the app and tried it myself and am seeing the same thing. I suspect this is primarily an issue with the app since the link is correct and still valid. This is the link in the README.md https://github.com/GoogleContainerTools/skaffold/blob/master/examples for context.

**Comment by IsaacPD** [comment]
I tried using a non-relative link on my branch https://github.com/IsaacPD/skaffold/tree/android-gh-app-readme and still got the same issue in the app. I'm imagining links to code directories in repos are not exactly working properly in the app but that's my best guess. 

I'll close this issue since it is not something under our control.

**Comment by tejal29** [comment]
Looks like @IsaacPD answered the question. Adding comment for triage party.
