### ISSUE TITLE
Expose name of kubectl command as configuration option

### ISSUE THREAD

**Issue by crimeminister** [GoogleContainerTools/skaffold#5209]
From looking at the source it appears that the name of the `kubectl` command is [hard-coded](https://github.com/GoogleContainerTools/skaffold/blob/ff33ac0a47dde7bc035eec1be8ae1fce01fa97d9/pkg/skaffold/kubectl/cli.go). Would it be possible to expose this name as a configuration option? This should allow for easy usage of `kubectl`-alikes like [microk8s](https://microk8s.io/) that have non-standard tool names to avoid conflicts, e.g. `microk8s.kubectl`.

**Comment by nkubala** [comment]
@crimeminister interesting request. one issue with this is that we rely on several utilities of `kubectl` for various things in skaffold (e.g. port forwarding, pod logging, etc.) and we wouldn't be able to guarantee that whatever binary a user provides fulfills that spec. out of curiosity, have you tried replacing `kubectl` in your `PATH` with your alternative and trying skaffold on that? i'm wondering if things work as expected :)

allowing custom scripts for deployments would probably address this indirectly, but realistically that might not happen for a little while.

**Comment by crimeminister** [comment]
> out of curiosity, have you tried replacing `kubectl` in your `PATH` with your alternative and trying skaffold on that? i'm wondering if things work as expected :)

I'll give it a shot and see what (if anything) blows up. Now you've got me curious as to just how compliant some of the alternative `kubectl` implementations are w.r.t. the original. Custom scripts sound like an interesting avenue for future exploration, thanks for mentioning the eventual possibility.

**Comment by briandealwis** [comment]
This is an interesting idea.  The Google Cloud SDK includes a _dispatcher_ kubectl which looks at the cluster version and hands-off to corresponding `kubectl`.

But hard-coding a path into the `skaffold.yaml` would make it difficult to switch between clusters (e.g., from a local microk8s to GKE).

We could consider making this an option in the global configuration file (`~/.skaffold/config`) as a per-cluster option.

Closing this due to time, but we can re-open if someone is interested in contributing.
