### ISSUE TITLE
Status check should monitor single pod resources

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#5529]
Relates to #6686

### Expected behavior
`skaffold run` on our `getting-started` example will monitor the created pod for readiness before exiting succesfully

### Actual behavior
`skaffold run` just says "Deployments stabilized", but doesn't actually do any status checking on that pod

### Information

This is happening because we made a conscious decision to only monitor pods that are tied to deployments, since most people are not deploying standalone pods. Shouldn't be too difficult for us to extend this to individual pods though.

- Skaffold version:  Any version with status check, I tried on v1.20.0
- Operating system:  All, I'm on Mac OS Big Sur
- Installed via:  Built from source
- Contents of skaffold.yaml: Our getting started example

### Steps to reproduce the behavior

1. our getting-started example
2. `skaffold run`

**Comment by dhodun** [comment]
We ran into this when installing bitnami redis via stateful sets as well. So ideally this picks up more than an individual container, but also non-deployment artifacts like StatefulSet.

**Comment by chris13524** [comment]
We desire this feature as well. We are using the [NATS Helm chart](https://github.com/nats-io/k8s/tree/master/helm/charts/nats) and it uses a `StatefulSet` which Skaffold doesn't check for its status.

**Comment by chris13524** [comment]
Reading the use case for healthchecks [here](https://skaffold.dev/docs/workflows/ci-cd/#waiting-for-skaffold-deployments-using-healthcheck), I will add that our use case is using Skaffold for E2E tests. It would be convenient to be able to wait for Skaffold to emit the HTTP API field for `forwardedPorts` so that we know the workloads are ready to be tested. Currently we are waiting for `forwardedPorts` to be non-empty and then have a second loop to wait for NATS to be ready.

**Comment by tejal29** [comment]
Lets break this into two separate issues and add them to next milestone.

**Comment by briandealwis** [comment]
Added #6642 too.
