### ISSUE TITLE
add integration test with minikube in kokoro 

### ISSUE THREAD

**Issue by medyagh** [GoogleContainerTools/skaffold#5737]

**Comment by medyagh** [comment]
thank you @aaron-prindle for picking up this task, let me know if there was any issue with adding minikube to the kokoro or gh action

**Comment by aaron-prindle** [comment]
Are there any specific action items for the minikube+skaffold integration tests here?  Currently skaffold tests with a minikube cluster in its github actions here:
https://github.com/GoogleContainerTools/skaffold/blob/master/.github/workflows/integration-linux.yml#L75-L79

Is sufficient for the issue here?  Trying to understand what missing tests we might want to test w/ minikube+skaffold or what issues we have seen in the past that we might want to mitigate with additional testing.  Trying to better understand the work required here, thanks!

**Comment by medyagh** [comment]
hi @aaron-prindle the github action seems to be testing against an ancient version of minikube (v1.11.0) and that seems to only run on the release

and the one running on the PR has have run in 12 months https://github.com/GoogleContainerTools/skaffold/actions/workflows/PR.yaml

ideally it would be best to test PRs against latest minikube on HEAD
the binaries for minikube HEAD could be find here
```
https://storage.googleapis.com/minikube/latest/minikube-linux-amd64
or
https://storage.googleapis.com/minikube-builds/master/minikube-linux-amd64
``` 

and the release job would test agaisnt latest released minikube

the binaries for latest "released" minikube binary could be installed by
```
 curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
 sudo install minikube-linux-amd64 /usr/local/bin/minikube
```

**Comment by aaron-prindle** [comment]
Currently kokoro is used only for GCP related tests, this is the case because these tests take a much longer time.  As you noticed, the skaffold minikube tests are currently not in a good state:
- old minikube version
- not run on every PR
- do not block PRs but instead send an email on failure and have actually not been running // failing-prior due to dockerhub API rate limits

Currently my plan is to make the gh tests pull from minikube nightly/head (from talking to Brian it seems these you release these binaries but I am still poking around to find them),  get the tests healthy w/ the dockerhub API rate limits and run the tests per PR in a PR blocking fashion.    Alternatively we might move these tests from gh and use travis but I am still trying to understand the pros/cons
