### ISSUE TITLE
skaffold zsh command completion ends with `ShellCompDirectiveNoFileComp`

### ISSUE THREAD

**Issue by Nightreaver** [GoogleContainerTools/skaffold#5960]
### Steps to reproduce

- using zsh
- using `source <(skaffold completion zsh)` to load command completion
- hitting [TAB] during commands should print the actual commands, without ( I guess ) the ShellComp... output which can also be tabbed through

### Expected behavior

hitting [TAB] during commands should print only available commands/options

### Actual behavior

hitting [TAB] during commands print additional output. ie

```
~ skaffold deploy [TAB]
:0 Completion ended with directive: ShellCompDirectiveNoFileComp
```

hitting [TAB] again will result in

```
~ skaffold deploy :0
:0 Completion ended with directive: ShellCompDirectiveNoFileComp
```

and again

```
~ skaffold deploy Completion\ ended\ with\ directive:\ ShellCompDirectiveNoFileComp
:0 Completion ended with directive: ShellCompDirectiveNoFileComp
```

which are no valid command options

### Information

- Skaffold version: 1.25.0
- Operating system: Debian 20.04 LTS
- Installed via: binary download

**Comment by gsquared94** [comment]
able to repro on master branch.

**Comment by marckhouzam** [comment]
I've taken the liberty to investigate this issue. It turns out that skaffold sets both stdout and stderr to the same output stream in a `PersistentPreRun`.  This causes a problem for Cobra's `__complete` command which outputs a debugging line on stderr which is normally ignored, but since this line appears on stdout for skaffold, it appears as a (invalid) completion.

Skaffold does this here https://github.com/GoogleContainerTools/skaffold/blob/master/cmd/skaffold/app/cmd/cmd.go#L91

Is this behaviour on purpose?  I happens to be using the deprecated Cobra function `SetOutput()` which sets both stdout and stderr at the same time.  Should Cobra's `SetOut()` be used instead?  
See:
https://github.com/spf13/cobra/blob/9a432671fd847f0faa5a5e4d9f9350ae289db2ac/command.go#L238-L250

Another option is to change this behaviour just when the `__complete` command is called.
