### ISSUE TITLE
Travis build cache leads to build hangs

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6182]
Seeing build setup hangs more frequently now on Travis.  Here's an [example](https://api.travis-ci.com/v3/job/523337529/log.txt) of a failing build:
```
Setting up build cache
$ export CASHER_DIR=${TRAVIS_HOME}/.casher
$ Installing caching utilities
0.00s40.50sattempting to download cache archive
fetching PR.6161/cache--linux-xenial-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--go-1.15.x.tgz
fetching PR.6161/cache-linux-xenial-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--go-1.15.x.tgz
fetching PR.6161/cache--go-1.15.x.tgz
fetching master/cache--linux-xenial-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--go-1.15.x.tgz
found cache
adding /home/travis/.cache/go-build to cache
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

The workaround is to delete all of the [repo cache](https://app.travis-ci.com/github/GoogleContainerTools/skaffold/caches), but I needed to do it twice today!  

I didn't take a screenshot of the cache state, but certainly when there is a problem, several of the cache bundles are about 4gb in size.

We're caching `~/.cache/go-build`, and I wonder if this is a safe thing to do given the multiple platforms that we're building for (windows, mac, linux).  Maybe we should instead be caching the Go module cache `~/go/pkg`.

**Comment by ahmetb** [comment]
I am suspecting this might be a bug on TravisCI-side triggering when the caches reach a certain size, such as maybe network mount is getting stuck. 

Keeping the GOCACHE dir around should be safe for multi-platform compilation (as it's also used for same purpose while building on a single machine). But since the project uses go.mod, caching `~/go/pkg/mod` save quite some time downloading repos (without caching any object files and therefore ever getting huge).
