### ISSUE TITLE
Test flake `TestRunTail/nodejs`

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#6262]
```
/integration/TestRunTail/nodejs
time="2021-07-20T22:53:42Z" level=debug msg="getting client config for kubeContext: ``"
time="2021-07-20T22:53:42Z" level=info msg="Namespace: skaffold8zrzr"
time="2021-07-20T22:53:42Z" level=info msg="Running [skaffold run --namespace skaffold8zrzr --default-repo gcr.io/k8s-skaffold --tail] in examples/nodejs"
WARNING: Could not open the configuration file: [/root/.config/gcloud/configurations/config_default].
    util.go:419: timeout
time="2021-07-20T22:55:12Z" level=info msg="Ran [skaffold run --namespace skaffold8zrzr --default-repo gcr.io/k8s-skaffold --tail] in 1 minute 30.047 seconds"
    --- FAIL: TestRunTail/nodejs (90.12s)
```

**Comment by nkubala** [comment]
seeing this pretty frequently. strangely, it seems to only flake on the `TestRunTail` but not `TestRunTailDefaultNamespace`, the exact same test but running without a uniquely created namespace.

**Comment by nkubala** [comment]
thinking about this more, this is the only example we're running in this test that doesn't have a recurring log output. my guess is that the logs are attaching **after** the log line we're looking for (`Example app listening on port 3000!`), so it's never seeing this log line and timing out.

this example would be weird to update since no real app would print `listening on port XXX` in a loop, and fundamentally it it's testing the same thing as the `getting-started` example (`kubectl` deployment tails logs correctly), so i'll remove it.
