### ISSUE TITLE
Question: Use Bazel build for Helm with deploy

### ISSUE THREAD

**Issue by rohrit** [GoogleContainerTools/skaffold#6763]
I have a project where I build containers and helm charts using Bazel. I want to see if I can use scaffold to deploy the output of the Bazel built Helm chart. I could not figure out how to do this from the documentation and am hoping someone can tell me if this is possible using scaffold and point me in the right direction.

**Comment by nkubala** [comment]
@rohrit thanks for the question. can you provide more info about your project structure? skaffold.yaml if you have it, directory tree, contents of your Bazel build files and your kubernetes yamls if they exist.

what part of that setup specifically were you encountering friction with? skaffold supports Bazel natively, so i think you shouldn't have a problem getting it to build both your container images and also output helm charts to your local filesystem. it's possible that the way we compute deployment dependencies at runtime would have issue with your helm chart not being present (since it hasn't been built with Bazel yet), but it would be easier to help you if you could provide more information about your project setup.

**Comment by rohrit** [comment]
@nkubala , thank you for your response. The directory structure is shown below.

-- WORKSPACE
-- service1
     |__ BUILD.bazel
     |_ <go code>
-- service2
     |_ BUILD.bazel
     |_ <go code>
-- deploy
    |__ charts
         |_ BUILD.bazel
         |__ Chart.yaml
         |_ values.yaml
         |_ templates
             |_ <yamls>
-- skaffold.yaml

We build the service docker containers using Bazel as well as the Helm charts using Bazel. What I was expected from Skaffold was a way to use Bazel in build stage to build the containers followed by the Helm chart. According to the documentation at https://skaffold.dev/docs/pipeline-stages/builders/bazel/, Skaffold seems to support building containers with the bazel target.

Furthermore, I am not sure if we can take the results of the bazel build of the Helm chart (which is typically in a hazel-bin/deploy/charts/<chart_name>.tgz file) and pass that as the deploy target (it didn't seem apparent from the documentation at https://skaffold.dev/docs/pipeline-stages/deployers/helm/)

Please let me know if you need any further information.

**Comment by mmellin** [comment]
I too have this use case, basically the same as @rohrit and was wondering if support for the same exists. We build with bazel to stamp some dynamic information such as versions into the helm chart. I'd like skaffold to be able to build this artifact target then deploy it using `helm` from the resultant `bazel-bin/` directory.

**Comment by tejal29** [comment]
Thanks folks. Right now skaffold does not this capability to run a bazel target for deploy dependencies. 
Unfortunately we don't have bandwidth to do so. Contributions and design proposals are welcome as always.
