### ISSUE TITLE
`skaffold build` fails when attempting to docker COPY an empty directory

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#6810]
Curently if a Dockerfile attempt to COPY an empty directory into a file, skaffold build will fail even though this is valid.  This makes some valid Dockerfiles not usable with skaffold which is an issue as we hope to fully support all Dockerfiles.  Example steps to reproduce this issue taken from - https://github.com/GoogleContainerTools/skaffold/pull/6796#issuecomment-962691340:

Steps to reproduce:
cd into `skaffold/examples/docker-deploy/bert/`
```
mkdir test
# add following copy to Dockerfile
COPY test .
cd ..
skaffold build
Generating tags...
 - bert -> bert:151b8d3-dirty
 - ernie -> ernie:151b8d3
Checking cache...
 - bert: Not found. Building
 - ernie: Found Locally
Starting build...
Found [ed-ks2] context, using local docker daemon.
Building [bert]...
Sending build context to Docker daemon  3.072kB
Step 1/9 : FROM golang:1.15 as builder
 ---> 40349a2425ef
Step 2/9 : COPY main.go .
 ---> Using cache
 ---> 5bcddb464805
Step 3/9 : ARG SKAFFOLD_GO_GCFLAGS
 ---> Using cache
 ---> 0fe720d5c3d6
Step 4/9 : RUN go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -o /app main.go
 ---> Using cache
 ---> b0fa60be1cbd
Step 5/9 : FROM alpine:3.10
 ---> e7b300aee9f9
Step 6/9 : ENV GOTRACEBACK=single
 ---> Using cache
 ---> e850d4805844
Step 7/9 : COPY test .
unable to stream build output: COPY failed: file not found in build context or excluded by .dockerignore: stat test: file does not exist
```
Verify directory exists:
```
ls bert/
Dockerfile   main.go   src   test
```

Now, add a single file to the directory and try again:
```
touch bert/test/testfile
 skaffold build
Generating tags...
 - bert -> bert:151b8d3-dirty
 - ernie -> ernie:151b8d3
Checking cache...
 - bert: Not found. Building
 - ernie: Found Locally
Starting build...
Found [ed-ks2] context, using local docker daemon.
Building [bert]...
Sending build context to Docker daemon  3.584kB
Step 1/9 : FROM golang:1.15 as builder
 ---> 40349a2425ef
Step 2/9 : COPY main.go .
 ---> Using cache
 ---> 5bcddb464805
Step 3/9 : ARG SKAFFOLD_GO_GCFLAGS
 ---> Using cache
 ---> 0fe720d5c3d6
Step 4/9 : RUN go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -o /app main.go
 ---> Using cache
 ---> b0fa60be1cbd
Step 5/9 : FROM alpine:3.10
 ---> e7b300aee9f9
Step 6/9 : ENV GOTRACEBACK=single
 ---> Using cache
 ---> e850d4805844
Step 7/9 : COPY test .
 ---> 4c26c1bf872e
Step 8/9 : CMD ["./app"]
 ---> Running in 6c98a27efeca
 ---> 41b29bf39f5b
Step 9/9 : COPY --from=builder /app .
 ---> 69557d373998
Successfully built 69557d373998
Successfully tagged bert:151b8d3-dirty
```
It fails when the directory is empty.

**Comment by tarrow** [comment]
I believe I've also encountered this issue and can add some further details:
1. folders which are not empty but who "effectively" have empty contents because all the contents are ignored by `.dockerignore` seem to experience the same problem
1. a possible workaround appears to be adding `useDockerCLI: true` to the local build config section of the skaffold.yaml

This can be seen in the following testcase: https://github.com/tarrow/skaffold/tree/testcase6810/examples/docker-deploy which builds upon the testcase in the issue description.

running `skaffold build` fails for me locally until un-commenting the following line: https://github.com/tarrow/skaffold/blob/testcase6810/examples/docker-deploy/skaffold.yaml#L6 when the workaround seems to succeed

The real use-case where I independently encountered the issue (bug?) was building this repo: https://github.com/wbstack/api which resulted in the following directory being missing https://github.com/wbstack/api/tree/main/bootstrap/cache.
