### ISSUE TITLE
skaffold `ko` builder issues using `skaffold debug` functionality

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#6843]
In attempting to use the `ko` builder with the sample at `skaffold/integration/examples/ko` with Cloud Code's `Debug on Kubernetes` I was not able to successfully setup a debug flow.  The app builds and deploys properly and it serves requests but **none of the breakpoints trigger** as expected for `Debug on Kubernetes`.  My approach was as follows:
```
# modify cloud code skaffold binary to be latest skaffold built from HEAD
$ cp /usr/local/bin/skaffold-head ./.cache/cloud-code/installer/google-cloud-sdk/bin/skaffold
```

Open `/skaffold/integration/examples/ko` in VS Code (w/ Cloud Code installed):
```
$ ~/skaffold/integration/examples/ko  [main]$ code .
```

Add some breakpoints to the source code
![Screenshot 2021-11-11 11 13 45 AM](https://user-images.githubusercontent.com/1951658/141355575-0e6ec267-f208-4441-833c-513b23dee311.png)

Set the following values from the Cloud Code `Debug on Kubernetes` wizard
`image registry: gcr.io/aprindle-test-clusters`
`directory in the remote container where the program can be found: /ko-app`

From this setup, I am able to interact and see the images/deployments which work properly but none of the breakpoints seem to triggering.

```
aprindle@aprindle ~/skaffold/integration/examples/ko  [main]$ kubectl get po
NAME                  READY   STATUS    RESTARTS   AGE
ko-5dff4dbc6c-hkv27   1/1     Running   0          119s
```

![image](https://user-images.githubusercontent.com/1951658/141355948-5376e68a-4c84-426b-ae74-0e58d3d442fd.png)

**Comment by aaron-prindle** [comment]
@halvards 
perhaps something is incorrect in my setup or the args I passed to the wizard (eg: the remote container directory)?  Should apps built with ko work properly currently w/ `skaffold debug`?

**Comment by aaron-prindle** [comment]
Also, the suggested default path in the image (from the Cloud Code `Debug on Kubernetes` wizards) was `/home/nonroot`.  This should probably instead suggest `/ko-app` for ko applications (unless I am misunderstanding something)

**Comment by halvards** [comment]
Thanks for filing this @aaron-prindle!

This is caused by `ko` adding the `-trimpath` flag to `go build` if no build config is provided: https://github.com/google/ko/blob/5617d1ebf8560df778aa884fa328fe05f62bdb5e/pkg/build/gobuild.go#L562

A workaround right now is to use a non-empty `flags` config field, e.g. `["-v"]`.

But we should consider ensuring that this flag isn't set when debugging. I'll work with the `ko` team to determine if it's better to solve it upstream or in Skaffold.

For the VS Code launch configuration, the remote path should match the local path, so you can use a mapping such as this:

```json
            "debug": [
                {
                    "image": "your image name from skaffold.yaml",
                    "sourceFileMap": {
                        "${workspaceFolder}": "${workspaceFolder}"
                    }
                }
            ]

```

The "remote path" name is misleading IMO, it means "the source path used when compiling the code". For example, when building an image for a Go app using Docker, the full path to the source files will be different in the IDE (the key in the map above) to the full path used when compiling, since the compilation happens in a temporary container. For instance, a `Dockerfile` may include a statement such as `ADD . /src`. In that case, the mapping would be `"${workspaceFolder}": "/src"`.

IntelliJ IDEA and Goland appear to work out this mapping automatically.

In addition to a fix for the `-trimpath` flag, I'll create a PR to improve our docs and ko example.
