### ISSUE TITLE
gcloud not updating skaffold properly

### ISSUE THREAD

**Issue by thiago4int** [GoogleContainerTools/skaffold#6946]
### Expected behavior
Build
### Actual behavior
gcloud components install skaffold
All components are up to date.

### Information
skaffold dev
WARN[0000] Your Skaffold version might be too old. Download the latest version (1.35.0) from:
  https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.35.0  subtask=-1 task=DevLoop
parsing skaffold config: error parsing skaffold configuration file: unknown skaffold config API version "skaffold/v2beta26". Set the config 'apiVersion' to a known value. Check https://skaffold.dev/docs/references/yaml/ for the list of valid API versions. Otherwise, check that your skaffold version is up-to-date.
- Skaffold version: 
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

skaffold version
v1.34.0

**Comment by tejal29** [comment]
@thiago4int There is usually a lag between when skaffold new version is available Vs when it is available in gcloud. This is due to gcloud's weekly release schedule. This lag should not be more than 3-4 days. 

We understand this is a bit confusing to users however at this time, we don't have the capacity to work on this. 

We could potentially look into how user is managing skaffold i.e. via gcloud or not, and then not show this message. 
But like said, unlikely to be solved soon.
