### ISSUE TITLE
Build defaults to pushing images to docker.io 

### ISSUE THREAD

**Issue by feliperyan** [GoogleContainerTools/skaffold#6988]
### Expected behavior

Using `skaffold build` on https://github.com/GoogleContainerTools/skaffold/tree/main/examples/buildpacks-python builds a docker image locally.

### Actual behavior

Skaffold tries to push the newly built image to `docker.io` resulting in 

```
*** Images (347dad488020):
      fryan-skaff-bp-python:latest
Adding cache layer 'google.python.runtime:python'
Adding cache layer 'google.python.pip:pip'
Adding cache layer 'google.python.pip:pipcache'
The push refers to repository [docker.io/library/fryan-skaff-bp-python]
83d85471d9f8: Preparing
...
denied: requested access to the resource is denied
```

### Information

- Skaffold version:   **v1.35.1**
- Operating system:  **Debian GNU/Linux 10 (buster)**
- Installed via:  **curl of executable on skaffold.dev**
- Contents of skaffold.yaml: refer to https://github.com/GoogleContainerTools/skaffold/tree/main/examples/buildpacks-python 

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by halvards** [comment]
Skaffold loads the built image to a Docker daemon only if the current kubecontext points to a local cluster: https://skaffold.dev/docs/environment/local-cluster/#auto-detection

Otherwise, Skaffold attempts to push the image to a registry. You can set a default prefix for images to tell Skaffold where to publish, to avoid repeating the registry name for each image: https://skaffold.dev/docs/environment/image-registries/

If you want to hardcode the push/no-push behavior for local builders, you can set the `push` field in your `skaffold.yaml`: https://skaffold.dev/docs/references/yaml/#build-local-push

**Comment by gsquared94** [comment]
Closing as https://github.com/GoogleContainerTools/skaffold/issues/6988#issuecomment-1004553525 addresses the issue raised and we don't intend to make any changes to this behavior. Let us know if you feel otherwise.
