### ISSUE TITLE
Debugging With Skaffold

### ISSUE THREAD

**Issue by FsocietyDewit62** [GoogleContainerTools/skaffold#7164]
### Information

- Skaffold version: 
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by aaron-prindle** [comment]
@FsocietyDewit62 can you update the description here with information regarding the issue you encountered debugging with skaffold including:
- the error encountered
- the steps to reproduce the issue
- any configuration/project files that can be shared to help reproduce this

thanks

**Comment by aaron-prindle** [comment]
@FsocietyDewit62 can you describe the issue you encountered or feature request you are describing in more detail? I'm going to close this issue here but feel free to open another with more information describing what `Debugging with Skaffold` support you desire or possible issue you have encountered. Thanks
