### ISSUE TITLE
API repo releases information is missing "assets" since version v1.35.3

### ISSUE THREAD

**Issue by JohnKDay** [GoogleContainerTools/skaffold#7165]
Using ansible to download and install the latest version of skaffold, but since 1.35.3, the api does not contain the "assets" information anymore and my playbook is broken.

```
  - name: Get latest url for linux-amd64 release for skaffold
     uri:
       url: https://api.github.com/repos/GoogleContainerTools/skaffold/releases/latest
       return_content: true
       body_format: json
     register: skaffold_response

   - name: Download and install skaffold
     get_url:
       url: "{{ skaffold_response.json | to_json | from_json| json_query(\"assets[?ends_with(name,'linux-amd64')].browser_download_url | [0]\") }}"
       mode: 555
       dest: /usr/local/bin/skaffold
     debugger: on_failed
```
### Information

Last API release with "assets" information:
[v1.35.2](https://api.github.com/repos/GoogleContainerTools/skaffold/releases/tags/v1.35.2)

Missing "assets" information examples:
[v1.35.3](https://api.github.com/repos/GoogleContainerTools/skaffold/releases/tags/v1.35.3)
[latest](https://api.github.com/repos/GoogleContainerTools/skaffold/releases/latest)

Failure example:
```

TASK [Get latest url for linux-amd64 release for skaffold] ***************************************************************************************************************************
ok: [localhost]

TASK [Download and install skaffold] *************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "unknown url type: ''", "status": -1, "url": ""}
```

**Comment by tejal29** [comment]
@JohnKDay , [v1.35.2](https://api.github.com/repos/GoogleContainerTools/skaffold/releases/tags/v1.35.2)  and [v1.35.3](https://api.github.com/repos/GoogleContainerTools/skaffold/releases/tags/v1.35.3) were released only for fixing vulnerabilities in the skaffold container image. The binaries had no effect on it and hence the assets were not included.

I am wondering if you have a process of consuming the latest. Please add more details and we can think of something to not break your pipeline due to vulnerability patches.

**Comment by tejal29** [comment]
closed as won't fix. Please comment to re-open
