### ISSUE TITLE
Skaffold should allow users to provide additional options to pack build

### ISSUE THREAD

**Issue by pcperera** [GoogleContainerTools/skaffold#7346]
How can I pass the **--clear-cache** argument to the buildpacks in skaffold.yaml ?

![image](https://user-images.githubusercontent.com/15628990/165734826-b228146c-b034-44f2-a002-289f8f85ddb8.png)

**Comment by aaron-prindle** [comment]
This flag is not supported currently in our config:
https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/build/buildpacks/lifecycle.go#L99-L110

Additinonally there is no way to pass the flag through at the moment.  A currently hacky workaround would be to modify https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/build/buildpacks/lifecycle.go#L99-L110:
```
	if err := runPackBuildFunc(ctx, out, b.localDocker, pack.BuildOptions{
		AppPath:         workspace,
		Builder:         builderImage,
		RunImage:        runImage,
		Buildpacks:      buildpacks,
		Env:             env,
		Image:           latest,
		PullPolicy:      pullPolicy,
		TrustBuilder:    func(_ string) bool { return artifact.TrustBuilder },
		ContainerConfig: cc,
		ClearCache: true, // <------ add this line
```
and re-build this from source

Currently when we submit the `PackOptions` to buildpack, we do not have a related config option for `PackOptions.ClearCache`.  If you want to attempt to add it, feel free to submit a PR plumbing a flag/config-option through to the linked code there to support `PackOptions.ClearCache`.

**Comment by MarlonGamez** [comment]
Hi, I'm renaming and relabelling this issue to be a feature request. PRs are welcome for this change! This is a pretty simple change as far as I'm aware

**Comment by CuriousCorrelation** [comment]
@aaron-prindle Hey I'd like to take a stab at this issue. First look seems to suggest that this should be fixed by passing a bool field to `runPackBuildFunc`

``` go
 108 │      TrustBuilder:    func(_ string) bool { return artifact.TrustBuilder },
 109 │      ClearCache:      clearCache,
 110 │      ContainerConfig: cc,

```

`clearCache` var could be picked up from `a *latest.Artifact`

``` go
  50 │   artifact := a.BuildpackArtifact
  51 │   workspace := a.Workspace
  52 │   clearCache := a.ClearCache
```

defined in `latest/config.go`

``` go
  935 │   // Example: `["linux/amd64", "linux/arm64"]`.
  936 │   Platforms []string `yaml:"platforms,omitempty"`
+ 937
+ 938 │   // Clears old cache volume associated with the specific image
+ 939 │   // and supplies a clean cache volume.
+ 940 │   ClearCache bool `yaml:"clearCache,omitempty"`
  941 }
  942
```

--- 

Finally we could provide this config like this 

``` yaml
platforms: [...]
clearCache: true
```

---

Does this seem reasonable? Let me know if I am missing something, if ergonomics needs to be changed.

**Comment by aaron-prindle** [comment]
@CuriousCorrelation that would be great!  Yes, the steps you have outlined make sense with some minor changes:
- Currently the schema option `clearCache` that you have outlined above are at the "top level" and ideally the schema option would be nested under build.artifacts.buildpacks (similar to `trustBuilder`)

instead of:
``` yaml
platforms: [...]
clearCache: true
```

nested under build.artifacts.buildpacks (so build.artifacts.buildpacks.clearCache)
```
apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks-node
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
      trustBuilder: true
      clearCache: true # <--- here
```

This would mean that instead of adding the value as suggested in `latest/config.go` this would be added to a place similar to where `TrustBuilder` is:
https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/schema/latest/config.go#L1091-L1092

`latest/config.go`
```
// BuildpackArtifact *alpha* describes an artifact built using [Cloud Native Buildpacks](https://buildpacks.io/).
// It can be used to build images out of project's sources without any additional configuration.
type BuildpackArtifact struct {
...
	// TrustBuilder indicates that the builder should be trusted.[2 years ago • David Gageot [[buildpacks] Support trusted builders (#4273)]](https://sourcegraph.com/github.com/GoogleContainerTools/skaffold/-/commit/3f391224a1d52cd7357150c2e54326983feb8a9c)
	TrustBuilder bool `yaml:"trustBuilder,omitempty"`
	
	// ClearCache here ...
```

**Comment by CuriousCorrelation** [comment]
@aaron-prindle Thank you for the detailed description. Have a look at the draft I proposed whenever you have some time and let me know if everything looks alright.
