### ISSUE TITLE
Fix/implement multi-module support for the `manifests` schema configuration

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7873]
Currently Skaffold's `manifests` field does not properly implement multi-module support.
See the code here:
https://github.com/GoogleContainerTools/skaffold/blob/1f5af29273e2938c66311fcc22ddf0fcceeeffd7/pkg/skaffold/runner/runcontext/context.go#L295-L297

This bug tracks properly updating the `manifests` section of a skaffold.yaml w/ multi-module support (vs how it currently works which is just using the root modules values and disregarding the other values)

Thanks @spstarr and @gsquared94 for repro-ing and root-causing this issue

**Comment by gsquared94** [comment]
I think you have to do away with `GetRenderConfig()` method. And in the `GroupRenderer` maintain a `[]Hook` instead of just a single `Hook`.  
Something like this in renderer.go:


<img width="1740" alt="image" src="https://user-images.githubusercontent.com/39389231/191416453-c6b9c9cd-d60b-4cdb-957e-da93c330b2a3.png">

Then we need to decide if we want to iterative run each `Deploy`'s pre and post hook around that deployer, or run all aggregate pre-hooks, then all the deployers as they are happening currently, then all the aggregate post hooks
