### ISSUE TITLE
How to use envTemplate in github action?

### ISSUE THREAD

**Issue by OpenAIMP** [GoogleContainerTools/skaffold#8015]
Hi,

I'm running skaffold from github action but want to use skaffold's tagging policy option of envTemplate. Is there a way to pass environment variables to skaffold from github action?

Thx.

**Comment by MarlonGamez** [comment]
hey @OpenAIMP, currently that exactly functionality would only be possible through a multi module/config skaffold setup, because we currently only support one tagpolicy per module. So you'd have to create one module for each of the images that you want to give a unique tag to.

Here is some more documentation on multi config skaffold setups https://github.com/GoogleContainerTools/skaffold/issues/8015
