### ISSUE TITLE
docker image for v2.0.2 is missing

### ISSUE THREAD

**Issue by stefan-schweer** [GoogleContainerTools/skaffold#8114]
### Expected behavior

docker pull gcr.io/k8s-skaffold/skaffold:v2.0.2 works

### Actual behavior

Error response from daemon: manifest for gcr.io/k8s-skaffold/skaffold:v2.0.2 not found: manifest unknown: Failed to fetch "v2.0.2" from request "/v2/k8s-skaffold/skaffold/manifests/v2.0.2".

**Comment by aaron-prindle** [comment]
Thanks for flagging this, we recently changes our CI/CD system and it seems automatically releasing the image when we cut a release was dropped in our changes.  I have manually triggered our image release and it is now available:
gcr.io/k8s-skaffold/skaffold:v2.0.2 

I have filed #8120 to fix our CI/CD for our release process so that there should  not be an issue like this in the future
