### ISSUE TITLE
[release] Fix skaffold release process to also create the release docker image

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8120]
Currently our recently changed CI/CD for the release process dropped creating the skaffold docker image - #8114.   This issue tracks updating/fixing our CI/CD for the release process to also create the skaffold docker image

**Comment by ericzzzzzzz** [comment]
Hi @aaron-prindle , I checked our could build configuration for docker image release,  that release job is configured to be triggered by ``push tag`` with rule ``v[0-9]+\.[0-9]+\.0`` , looks like it was intentional that we don't release patch version docker image, but I check several releases, each release is with a docker image release, even though for patch release. Have we been manually triggering that cloud build job for building docker release image for patch release? Not sure I was looking the right place.

**Comment by aaron-prindle** [comment]
Yes, we have been manually releasing these images for the past releases.  Thanks for checking this, that regex is incorrect then.   We definitely want an image for all releases including patch releases (X.Y.<patch-release-#>).  I've updated the tag regex to be:
`v[0-9]+\.[0-9]+\.[0-9]+` which should match all of the relevant tags

**Comment by aaron-prindle** [comment]
Closing (fixed) from the above
