### ISSUE TITLE
The v2 module path should be `github.com/GoogleContainerTools/skaffold/v2`

### ISSUE THREAD

**Issue by sethrylan** [GoogleContainerTools/skaffold#8161]
### Expected behavior

We can use `go get` to download the skaffold packages.

As per [the go documentation](https://go.dev/doc/modules/version-numbers#major-version), any major version updates should be reflected in the module's path.

### Actual behavior

```console
➜ go version
go version go1.19.3 linux/amd64

➜ go get github.com/GoogleContainerTools/skaffold@v2.0.2                                               
go: github.com/GoogleContainerTools/skaffold@v2.0.2: invalid version: module contains a go.mod file, so module path must match major version ("github.com/GoogleContainerTools/skaffold/v2")

➜ go get github.com/GoogleContainerTools/skaffold/v2@v2.0.2
go: github.com/GoogleContainerTools/skaffold@v2.0.2: invalid version: module contains a go.mod file, so module path must match major version ("github.com/GoogleContainerTools/skaffold/v2")
```

### Information

- Skaffold version: v2.0.2
- Operating system: 18.04.1-Ubuntu
- Installed via: `go get`
- Contents of skaffold.yaml: N/A

**Comment by aaron-prindle** [comment]
@sethrylan thanks for flagging this.  I see you have a draft PR here:
https://github.com/GoogleContainerTools/skaffold/pull/8162

Lmk if you need anything on our end.  Also is there a reason that PR goes to `v2` branch vs `main` branch (does the Skaffold module path `github.com/GoogleContainerTools/skaffold/v2` relate to the branch used?  Sorry if this is obvious, need to read up on modules - it's a been a while since we have had to muck with them outside of `go get`)

**Comment by sethrylan** [comment]
> is there a reason that PR goes to v2 branch vs main branch (does the Skaffold module path github.com/GoogleContainerTools/skaffold/v2 relate to the branch used?

Nope! That was my mistake. The `v2` branch is old, and `main` is the correct target. I've made another pass at this issue with https://github.com/GoogleContainerTools/skaffold/pull/8169

That PR is ready for CI and review. Let me know what you think.
