### ISSUE TITLE
`skaffold version` in CLI does not display anything

### ISSUE THREAD

**Issue by SdgJlbl** [GoogleContainerTools/skaffold#8391]
### Expected behavior
According to `skaffold -h`, `skaffold version` should display the version information. I think it was the case before (can't remember the exact version), but it's not the case in `2.1.0`. 
 

### Actual behavior
`skaffold version` returns an empty line.

### Information

- Skaffold version:  2.1.0 (version obtained via `brew info skaffold`)
- Operating system:  macOS Monterey (12.6.2)
- Installed via:  brew
- Contents of skaffold.yaml:  NA

### Steps to reproduce the behavior

```
brew install skaffold
skaffold version
```

**Comment by aaron-prindle** [comment]
@SdgJlbl thanks for flagging this, there was in issue during our initial release process for `v2.1.0`.  We cut the `v2.1.0` branch but then discovered this bug so we do not officially release the binaries into our release buckets or create the GH release and re-created the `v2.1.0` branch with this fix:

![image](https://user-images.githubusercontent.com/1951658/215828066-18dff4c5-16a7-43a0-a92f-ff90bb0449eb.png)

The issue that for a brief period the `v2.1.0` branch existed with this bug and `brew` watches for new branches so it used the Skaffold branch that our team did not release binaries from.  This is fixed @ HEAD and in the binaries that we released in Github for `v2.1.0`.  For `brew `users this should be fixed with our next release - `v2.2.0`.  Sorry for the inconvenience here, I am not aware of a simple way to change the binary brew distributes and it might additionally be confusing for `brew` to have 2 `v2.1.0` binaries it hosted.

If you are able to swap the binary in brew, you can download the Mac OS binary from our `v2.1.0` GH Release page - https://github.com/GoogleContainerTools/skaffold/releases/tag/v2.1.0
and this should be fixed there.  

Closing this as this is already fixed @ HEAD and in our officially hosted binaries (non-brew).

**Comment by stooboo** [comment]
FYI this broke https://github.com/GoogleCloudPlatform/cloud-code-vscode on my Mac :-( 
installing from your link (https://github.com/GoogleContainerTools/skaffold/releases/tag/v2.1.0) fixed it
cheers

**Comment by aaron-prindle** [comment]
@stooboo thanks for the info that this issue broke https://github.com/GoogleCloudPlatform/cloud-code-vscode on your Mac.  If you don't mind, could you describe your  setup and if you think this would affect other users?  My understanding is that cloud code has it's own skaffold binary that is managed via a bundled version of gcloud.  Did you modify the extension to use the skaffold binary from `brew` or was this via a "default"/standard installation?  Just trying to understand if this might be a bigger issue worthy of releasing a `v2.1.1` release for just to fix brew users for now (vs waiting ~1-2 weeks for `v2.2.0`).  Thanks!

**Comment by stooboo** [comment]
Hi @aaron-prindle 

I already had skaffold installed via brew .. so when i added the VSCode plugin about a year ago, I originally disabled the plugin's auto-update setting 
(I had to use skaffold v1.39 I think it was - it's a work Mac)

I noticed that cloudcode wasn't working today (recently I'd done brew upgrade and there was a Mac os update (not Ventura).. so wasn't sure what had caused this)
It was getting stuck while checking skaffold version

I uninstalled skaffold, 
tried VSCode again this time with the auto-update turned on which should have installed skaffold.. no joy.. 

reinstalled skaffold via brew .. no joy

reinstalled xcode cli tools too as that had been mentioned on another issues page on cloudcode's repo...still no joy

I stumbled onto this issue by a bit of judicious/random googling...
Followed your link ...
and .. Yippee .. I'm back up and running 

So thankyou again

**Comment by aaron-prindle** [comment]
Thanks for the info @stooboo, appreciate it.  Sorry for the inconvenience here, I think most users shouldn't be impacted then given the above info.  We will get a `v2.2.0` release out soon to help with `skaffold version` for `brew` users, I don't think it makes sense currently to do a patch release for this currently.

**Comment by stooboo** [comment]
No worries - it's a big world out there .. lots of things go wrong

I've got a workaround so I'm happy 👍

**Comment by aaron-prindle** [comment]
[ignore] Making triage bot happy
