### ISSUE TITLE
Kaniko "Flag --snapshotMode is deprecated. Use: --snapshot-mode"

### ISSUE THREAD

**Issue by whyevenquestion1t** [GoogleContainerTools/skaffold#9453]
### Expected behavior
everything works and the flag is passed to kaniko image as an argument 
### Actual behavior
--snapshotMode is deprecated
### Information
https://github.com/GoogleContainerTools/kaniko/issues/2408 - they changed the naming for the same flag, so now when I use kaniko with skaffold, i am not able to provide desired configuration to Kaniko 

The documentation still refers to the old flags as well, which is misleading: https://skaffold.dev/docs/references/yaml/#build-artifacts-kaniko-snapshotMode
- Skaffold version: 
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by sherman-yang** [comment]
Why always change the naming? this caused to have to change thousands of repo configuration.

before changed the name from  executor:**debug-vx.xx.x** to executor:**vx.xx.x-debug**. 
this time again?

Hundreds of projects suddenly stalled just because their name was changed.

not sure whether you're artists or engineers. 
Thank you for keeping me busy and ensuring I don't get laid off.
